### ISSUE TITLE
anamorphic bloom

### ISSUE THREAD

**Issue by JoubaMety** [rre36/ShaderpackIssueTracker#1]
**Is your feature request related to a problem? Please describe.**
git

**Describe the solution you'd like**
joubaited

**Describe alternatives you've considered**
rrena

**Additional context**
von brennerburg

**Comment by rre36** [comment]
![really](https://user-images.githubusercontent.com/15215556/107242861-b902b600-6a2c-11eb-8abb-47a900b03e32.gif)

**Comment by 20pero** [comment]
this is what my gmail gonna look like from now on. sick.

**Comment by rre36** [comment]
hmm
