### ISSUE TITLE
ma rain reflections in nostalgia where

### ISSUE THREAD

**Issue by andywithcatz** [rre36/ShaderpackIssueTracker#10]
**Describe the bug**
title

**To Reproduce**
1. enable nostalgia 3.0
2. /weather rain
3. profit

**Expected behavior**
rain ssr

**Screenshots**
https://imgur.com/a/kGmUXhP

**Environment (please complete the following information):**
Optifine Version: g7
Minecraft Version: 1.16.5
Shaderpack Version: 3.0
Graphics Card and Driver Version: rtx 2060 latest drivers
Operating System: windows 10
CPU: ryzen 7 1700X
Amount of System Memory (total and assigned to Java): uh

**Comment by rre36** [comment]
fixed in upcoming hotfix
