### ISSUE TITLE
Conduits and Lights

### ISSUE THREAD

**Issue by iamthebasher** [rre36/ShaderpackIssueTracker#101]
**Describe the bug**
"minecraft:conduit" and "minecraft:light[level=x]" emit light when in hand but not when placed

**To Reproduce**
place a conduit or minecraft light block

**Expected behavior**
each of the aforementioned blocks to emit light

**Screenshots**
n/a

Environment (please complete the following information):
Iris 1.6.16
Minecraft 1.20.4
version: KappaPT_P18b_2024-3-6_23.33
4gb allocated to minecraft
Graphics Card and Driver Version: OpenGL renderer string: AMD Radeon RX 7800 XT (radeonsi, navi32, LLVM 17.0.6, DRM 3.57, 6.7.7-200.fc39.x86_64)
Operating System: Fedora 39
CPU: Ryzen 7 5700x

**Comment by rre36** [comment]
Conduits are not rendered as blocks, thus not included in the voxel data used for path tracing
