### ISSUE TITLE
allow Mac player to use the shader packs with iris

### ISSUE THREAD

**Issue by Sideplate1000-Dev** [rre36/ShaderpackIssueTracker#105]
**Is your feature request related to a problem? Please describe.**
when turning on the shaders with iris shaders 1.6.17 on 1.20.4 you get a error message saying 
![Image 20-4-2024 at 12 17 PM](https://github.com/rre36/ShaderpackIssueTracker/assets/107785575/2fa3f732-e13d-439e-a878-ba1eaf27a5c8)
The shaderpack failed to load! Please report the error to the shader developer.

**Describe the solution you'd like**
I would want to have the shaders like kappa and nostalgia working with macOS minecraft.

**Describe alternatives you've considered**
other than just finding a new shader pack other that one of these I don't think there is a alternative.

**Additional context**
the error message copy message. 
composite4.vsh: composite4.vsh: ERROR: 0:1: '' :  version '430' is not supported
ERROR: 0:1: '' : syntax error: #version
ERROR: 0:2: '' :  #version required and missing.

**Comment by rre36** [comment]
Mac is explicity not supported with my packs due to technical reasons and because I have no way of testing anything for it.

**Comment by Sideplate1000-Dev** [comment]
oh ok well thanks anyway
