### ISSUE TITLE
Lensflare not working correctly

### ISSUE THREAD

**Issue by XenoxYT** [rre36/ShaderpackIssueTracker#11]
**Describe the bug**
Sun lens flare not Working correctly

**To Reproduce**
1. Look at the Water and you see.

**Expected behavior**

The Lensflare only work for the Water reflection (This is not normal) but not for the sun.

**Screenshots**
If applicable, add screenshots to help explain your problem. Preferrably with the F3 Screen being open.

![Badlion Client Screenshot 2021 03 03 - 17 03 14 77](https://user-images.githubusercontent.com/78287711/109835793-d6016200-7c43-11eb-88f1-1fbe6f3a58f0.png)
![Badlion Client Screenshot 2021 03 03 - 17 03 13 24](https://user-images.githubusercontent.com/78287711/109835796-d7328f00-7c43-11eb-9437-2643c3e0cbc1.png)
![Badlion Client Screenshot 2021 03 03 - 17 03 12 06](https://user-images.githubusercontent.com/78287711/109835797-d7328f00-7c43-11eb-9484-4ae2b0920e34.png)

**Environment (please complete the following information):**
Optifine Version: G7
Minecraft Version: 1.16.5
Shaderpack Version: Nostalgia 3.0
Graphics Card and Driver Version: NVIDIA RTX 2060 with the latest driver
Operating System: Windows 10
CPU: AMD Ryzen 5 2600x
Amount of System Memory (total and assigned to Java): 8GB and total 16GB of ram

**Additional context**
I apologize for my bad Englisch. I´m German. @rre36

**Comment by rre36** [comment]
![2021-03-04_11 56 51](https://user-images.githubusercontent.com/15215556/109953742-bff5af00-7ce0-11eb-9ee1-3c36f02ec458.png)
works on my end if the sun is not covered by clouds

**Comment by XenoxYT** [comment]
The Problem can be my texturepack because it changes the sun.
