### ISSUE TITLE
Campfire smoke can't be seen through black-stained glass blocks

### ISSUE THREAD

**Issue by kazarmy** [rre36/ShaderpackIssueTracker#111]
**Describe the bug**
Campfire smoke can't be seen through a black-stained glass block platform.

**To Reproduce**

See screenshot. Campfire is sitting on hay bale on a black-stained glass block roof, and player is looking at it from underneath the roof.

**Expected behavior**
Campfire smoke is seen.

**Screenshots**

![NostalgiaVX-campfire-smoke](https://github.com/rre36/ShaderpackIssueTracker/assets/12002672/f0afd0ea-7e9a-4221-ba03-b4f166a34fa5)

**Environment (please complete the following information):**

Iris Version: 1.6.11
Minecraft Version: 1.19.4
Shaderpack Version: NostalgiaVX P9a
Graphics Card and Driver Version: GTX 850M, 527.56
Operating System: Windows 10
CPU: Core i7-4710HQ
Amount of System Memory (total and assigned to Java): 16gb total / 8gb assigned

**Additional context**

Shader settings:
```
USE_FOG_LPV=true
pomShadowSamples=32
reflectionsAtrousEnabled=true
labEmissionMode=1
voxelPT_ReflectionsEnabled=true
pomEnabled=true
indirectResReduction=1
subsurfaceScatterMode=3
resourcepackReflectionsEnabled=true
SVGF_RAD=2
textureAoEnabled=true
UseLightleakPrevention=true
VX_MAX_WIDTH=256
pomSamples=512
slopeNormalCalculation=true
vertexAttributeFix=true
```

Loaded resourcepacks:

![mc-rp](https://github.com/rre36/ShaderpackIssueTracker/assets/12002672/3857b5dc-065a-44cb-ad5f-b636ba0e96a7)

Mods:

![mc-mods](https://github.com/rre36/ShaderpackIssueTracker/assets/12002672/62e16e34-5459-4279-a1f6-89ea8ea70056)
Fabric launcher is at version 0.15.11.

**Comment by ciaens** [comment]
This isn't a shader problem, but more a sodium issue (translucency sorting I believe, fixed in [future sodium 0.6.0](https://discord.com/channels/602796788608401408/1077645005042233374/1246960539976994896)), not related to the shader.
![2024-06-28_20 11 04](https://github.com/rre36/ShaderpackIssueTracker/assets/111684368/43abbab4-ba90-4d4a-bda3-c9a2787d646b)
![2024-06-28_20 11 09](https://github.com/rre36/ShaderpackIssueTracker/assets/111684368/5800e659-6691-4e97-aee9-05f6390b1045)

**Comment by kazarmy** [comment]
Oh this is not about the smoke going transparent, it's about seeing the smoke that is behind the glass. A shader can definitely do this (MakeUp Ultra Fast v.8.9f):

![MakeUp-campfire-smoke](https://github.com/rre36/ShaderpackIssueTracker/assets/12002672/21391f41-2359-437a-b0f3-94d908fb5161)

If shaders are disabled, the Quality->Graphics setting needs to be set to Fabulous! :

![Fabulous!-campfire-smoke](https://github.com/rre36/ShaderpackIssueTracker/assets/12002672/e20125cb-56fa-469a-b075-e78a5e80ac73)

**Comment by kazarmy** [comment]
I see that MakeUp Ultra Fast uses `particles.before.deferred = true` which works (for it) for smoke particles but not for rain particles.

**Comment by rre36** [comment]
That is a classic limitation of translucency rendering, since I can only really render a single layer of translucency properly with how NostalgiaVX works. Unlikely to change soon.
