### ISSUE TITLE
It's REALLY HARD to see in high contrast situations

### ISSUE THREAD

**Issue by MrWonderless** [rre36/ShaderpackIssueTracker#113]
KAPPA SHADERS.
In night situations you can make less shiny to an acceptable rate, setting all the block light strenght to minimum... But when you're in front of any light source, even the ones with low light level, you can't see anything, and it's almost imposible to set it propperly, when you adjust all the settings to see something, everything else looks weird, and when it's day that settings have less sense. I've tried for hours and days, but nothig works. The shaders have serious troubles with light contrast. That's such a shame because everything looks amazing on day, probably the best shader I've seen.

**To Reproduce**
1. Go to any light source
2. See to any place while the light source is in field of view

**Expected behavior**
Everything should be visible, not black

**Screenshots**
<img width="1920" alt="Base Profile Screenshot 2024 08 11 - 20 28 39 79" src="https://github.com/user-attachments/assets/9b3b143b-b4ad-4be9-aec4-5a4bfb6482d6">

**Environment (please complete the following information):**
It happen with every version of OptiFine and Iris
Minecraft Version: 1.20.1
Shaderpack Version: 5.2
Graphics Card and Driver Version: NVIDIA 4070 Super (Drivers 560.81)
Operating System: WIndows 11 Pro
CPU: Ryzen 7600
Amount of System Memory: Total 32 GB (Java 8GB)

**Additional context**
PD: When it's night, everything looks really desaturated, really diferent when it's day. It's really sad don't seeing colors.

**Comment by rre36** [comment]
Kappa uses a more realistic and thus wide dynamic range, you can tweak it in the settings to some extent, but nighttime actually being dark is intended. The desaturation you mention is called "purkinje effect" and can also be disabled in the settings.
