### ISSUE TITLE
Shadows are inverted

### ISSUE THREAD

**Issue by JosShepherd** [rre36/ShaderpackIssueTracker#114]
**Describe the bug**
All shadows generated are inverted (including the player's)

**Screenshots**
![output-onlinepngtools](https://github.com/user-attachments/assets/0bd3976c-b73b-476d-a372-6b6bf8c6daef)

**Environment please complete the following information:**
Optifine Version: (N/A) - This is an Iris modded version
Minecraft Version: 1.21
Shaderpack Version: v5.2
Graphics Card and Driver Version: RTX 2060 - 555.99
Operating System: Windows 11 Pro
CPU: Ryzen 5 3600
Amount of System Memory (total and assigned to Java): 8064mb

**Additional context**
This issue only appears to work in outdoor evnironments, if you are inside a cave, etc, then the shadows are fine.

**Comment by rre36** [comment]
Thats an issue caused by the latest iris version, there's a preview that works around that in my discord server, or alternatively you could wait for the next iris release to fix it.

**Comment by TheAllGuy** [comment]
Where abouts is the preview located on your discord server for how to work around it?

**Comment by JosShepherd** [comment]
> Where abouts is the preview located on your discord server for how to work around it?

Where abouts is the preview located on your discord server for how to work around it?
