### ISSUE TITLE
Sun is visible during the sunset when it´s raining.

### ISSUE THREAD

**Issue by XenoxYT** [rre36/ShaderpackIssueTracker#12]
**Describe the bug**

The sun is visible (Where are the cloud shadows)during the sunset when it´s raining.

**To Reproduce**
1. Run the Minecraft command /Weather rain
2. Set the time to 22500 and wait
3. See the Error

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Preferrably with the F3 Screen being open.
![Badlion Client Screenshot 2021 03 08 - 12 15 54 25](https://user-images.githubusercontent.com/78287711/110314691-7b338600-8008-11eb-8421-01045ef8d7da.png)

**Environment (please complete the following information):**
Optifine Version: 1.16.5 HD U G6
Minecraft Version: 1.16.5
Shaderpack Version: Kappa 3.1a
Graphics Card and Driver Version: NVIDIA RTX 2060 with the latest driver version
Operating System: Windows 10
CPU: AMD Ryzen 2600X
Amount of System Memory (total and assigned to Java):

Minecraft: 8gb
System: 16gb

**Additional context**

**Comment by XenoxYT** [comment]
![Badlion Client Screenshot 2021 03 08 - 12 22 54 79](https://user-images.githubusercontent.com/78287711/110315285-54298400-8009-11eb-89fd-f9adce06871b.png)

Here is a F3 Screenshot.

**Comment by rre36** [comment]
The sun is visible due to some internal workarounds for visual artifacts on cloud edges at the horizon. Will be less prominent during rain with 4.0.
