### ISSUE TITLE
Clouds Get Dark during the Day

### ISSUE THREAD

**Issue by XenoxYT** [rre36/ShaderpackIssueTracker#14]
**Describe the bug**
The Clouds get dark before the sun sets and before the dawn starts.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Preferrably with the F3 Screen being open.
![Badlion Client Screenshot 2021 03 16 - 19 44 18 74](https://user-images.githubusercontent.com/78287711/111363416-4ec6dc00-8690-11eb-9304-cdf2201293c4.png)
![Badlion Client Screenshot 2021 03 16 - 19 44 15 77](https://user-images.githubusercontent.com/78287711/111363418-4ff80900-8690-11eb-8157-310f4e0cf843.png)
![Badlion Client Screenshot 2021 03 16 - 19 44 09 92](https://user-images.githubusercontent.com/78287711/111363421-4ff80900-8690-11eb-8f98-f34402fbdb7b.png)
![Badlion Client Screenshot 2021 03 16 - 19 44 03 60](https://user-images.githubusercontent.com/78287711/111363424-50909f80-8690-11eb-9d48-09e6218a9fcf.png)

**Environment (please complete the following information):**
Optifine Version: 1.12.2 F5
Minecraft Version: 1.12.2
Shaderpack Version: Kappa 3.1 Lite and Kappa 3.1 (I´ve tested it with this as well)
Graphics Card and Driver Version: Upto date
Operating System: Win 10
CPU: AMD Ryzen 2600x
Amount of System Memory (total and assigned to Java): 8GB and 16GB total

**Additional context**

**Comment by rre36** [comment]
Does it also happen without mods? Might be something that interfers with optifine's shader backend.

**Comment by XenoxYT** [comment]
Yes for normal it works. I found the Mod out that made this very wrong looking scene. Because the Mod B3M (On Curseforge Вращение Земли Майнкрафтская) Was enabled and the Season was set to summer the Shader tought it was night but it was day (Because the Days are longer in Summer). But Thank you.

**Comment by XenoxYT** [comment]
And I Think it is very hard to make this mod compatible.
