### ISSUE TITLE
Bug with Entitys

### ISSUE THREAD

**Issue by XenoxYT** [rre36/ShaderpackIssueTracker#15]
**Describe the bug**
The Lightning of the Chest does not work it´s not affected by the sun.

**To Reproduce**
1. Load Kappa 4.0 T1
2. Look at a chest

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/78287711/112761728-fa5f1d00-8ffc-11eb-8880-a8c15f814af9.png)

**Environment (please complete the following information):**
Optifine Version: G7
Minecraft Version: 1.16.5
Shaderpack Version: 4.0 T1
Graphics Card and Driver Version: the newest. NVIDIA
Operating System: Win 10
CPU: AMD Ryzen 2600X
Amount of System Memory (total and assigned to Java): 8GB Minecraft and 16GB Total

**Additional context**

**Comment by FrontStreet** [comment]
Use the latest optifine preview version as RRE said in discord
