### ISSUE TITLE
Kappa Shader v3.1a doesn't work on Linux/mesa/AMDGPU

### ISSUE THREAD

**Issue by Sandai64** [rre36/ShaderpackIssueTracker#16]
**Describe the bug**
When choosing the shaderpack (with default settings) in the Shaders tab, the game reports an invalid program error (see log for details)

**To Reproduce**
1. Enable Kappa Shader v3.1a in the shaders tab
4. See the error in the game chat

**Expected behavior**
The shader should run

**Screenshots**
![Error in game chat](https://user-images.githubusercontent.com/42770217/112766513-816ac000-9012-11eb-9643-7f97c03e8c0b.png)

**Environment (please complete the following information):**
Optifine Version: 1.16.5-OptiFine_HD_U_G8_pre11
Minecraft Version: 1.16.5
Shaderpack Version: 3.1a
Graphics Card and Driver Version: OpenGL: Radeon RX 580 Series (POLARIS10, DRM 3.40.0, 5.11.10-arch1-1, LLVM 11.1.0), version 4.6 (Compatibility Profile) Mesa 21.0.1

Operating System: Arch Linux
CPU: AMD Ryzen 5 1600
Amount of System Memory (total and assigned to Java): 16 GB total, 6 GB assigned.

**Additional context**
[latest.log](https://github.com/rre36/ShaderpackIssueTracker/files/6217984/latest.log)

**Comment by platyple** [comment]
that's a known bug, mesa doesn't support unsigned integer buffers, the solution is to wait until 4.0 when rre reworks the lighting again ~~or use kappa lite~~.

**Comment by FrontStreet** [comment]
4.0 preview is already out, try it on her discord server.

**Comment by Sandai64** [comment]
> 4.0 preview is already out, try it on her discord server.

The issue still appears on Kappa_v4.0_T1 (With a different error message this time)
![2021-03-28_23 20 56](https://user-images.githubusercontent.com/42770217/112768410-52f1e280-901c-11eb-89a2-b6f2567a40a5.png)

Again, here is the log file for this new session : [latest.log](https://github.com/rre36/ShaderpackIssueTracker/files/6218091/latest.log)

**Comment by rre36** [comment]
Should be fixed in T2
