### ISSUE TITLE
Lightning is broken. Kappa 4.0 T1

### ISSUE THREAD

**Issue by XenoxYT** [rre36/ShaderpackIssueTracker#19]
**Describe the bug**

**To Reproduce**
place a see lantern into a dark room and go into a dark space of the room.
then you see the error.

**Expected behavior**

**Screenshots**
![Badlion Client Screenshot 2021 03 29 - 16 30 36 81](https://user-images.githubusercontent.com/78287711/112852965-b6c3ec00-90ac-11eb-8020-af3a53e42ff1.png)
![Badlion Client Screenshot 2021 03 29 - 16 30 35 92](https://user-images.githubusercontent.com/78287711/112852971-b7f51900-90ac-11eb-83d0-9c808e064a68.png)
![Badlion Client Screenshot 2021 03 29 - 16 30 27 10](https://user-images.githubusercontent.com/78287711/112852973-b88daf80-90ac-11eb-966c-bd3385a6314e.png)
![Badlion Client Screenshot 2021 03 29 - 16 30 25 46](https://user-images.githubusercontent.com/78287711/112852976-b88daf80-90ac-11eb-9037-08a1b0244d45.png)

**Environment (please complete the following information):**
Optifine Version:
Minecraft Version:
Shaderpack Version:
Graphics Card and Driver Version: Uptodate
Operating System: Win 10
CPU: Ryzen 2600x
Amount of System Memory (total and assigned to Java): 6gb to MC and 16GB total.

**Additional context**

**Comment by rre36** [comment]
Please specify your graphics card

**Comment by XenoxYT** [comment]
I Have a NVIDIA RTX 2060 and the latest driver. (Gaming Driver from NVIDIA)

**Comment by XenoxYT** [comment]
I´m playing on 1.16 with Optifine G8.

**Comment by xandercreates** [comment]
try G7, the previews are known to cause issues

**Comment by XenoxYT** [comment]
I tried it with G7 and it is not fixed.

**Comment by xandercreates** [comment]
check drivers even if you are sure theyre up to date

**Comment by XenoxYT** [comment]
Yeah there up to date

**Comment by XenoxYT** [comment]
Hopefully this get fixed soon. And I had only Optifine enabled.

**Comment by rre36** [comment]
Potentially caused by setting minimum ambient light to zero and should be fixed in T2

**Comment by XenoxYT** [comment]
Thanks RRe36. Great Work
