### ISSUE TITLE
Visual glitch on block textures

### ISSUE THREAD

**Issue by Quarthe** [rre36/ShaderpackIssueTracker#20]
**Describe the bug**
Black areas appearing on block textures, moving as the player moves, based on POV

**To Reproduce**
It appears when entering a world, it never disappears

**Expected behaviour**
Black areas not appearing on block textures

**Screenshots**
If applicable, add screenshots to help explain your problem. Preferably with the F3 Screen being open.
![2021-04-07_16 01 48](https://user-images.githubusercontent.com/82123436/113940745-2cba0880-97bb-11eb-80c6-16ca182b5e7f.png)
![2021-04-07_16 18 43](https://user-images.githubusercontent.com/82123436/113941759-f41b2e80-97bc-11eb-909c-2f889049800f.png)

**Environment (please complete the following information):**
Optifine Version: 1.16.5-Optifine_HD_U_G7
Minecraft Version: 1.16.5
Shaderpack Version: Kappa_v3.1a
Graphics Card and Driver Version: NVIDIA GeForce RTX 2070 27.21.14.6172
Operating System: Windows 10
CPU: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz   2.59 GHz
Amount of System Memory (total and assigned to Java): Total = 16gb, Java = 2gb

**Additional context**
Drivers are up to date, and this issue appears with few other shader packs

**Comment by rre36** [comment]
Reload the resourcepack, make sure normal and specular maps are enabled in the shaderpack selection screen and try the latest optifine preview.

**Comment by Quarthe** [comment]
Specular maps wouldn't enable, so I had to redownload Optifine. The issue is resolved, thanks.
