### ISSUE TITLE
White screen 

### ISSUE THREAD

**Issue by Stanislus4** [rre36/ShaderpackIssueTracker#21]
White screen with every version of minecraft and optifine

Optifine Version: tried latest and old versions
Minecraft Version: tried from 1.14.4 to 1.16.5
Shaderpack Version: Kappa P6
Graphics Card and Driver Version: GTX 1070 with latest driver 465.89
Operating System: Windows 10
CPU: AMD Ryzen 5 1600X
Amount of System Memory (total and assigned to Java):
32 total and 10 assigned

**Additional context 
I get black screen and error 1286 invalid frame buffer operation on 1.16.5 optifine HD G7 Ultra

**Comment by rre36** [comment]
KappaPT support happens through patreon or discord.
