### ISSUE TITLE
[Kappa 4.0 release] Rain puddles occur in hot bioms (savanna/desert)

### ISSUE THREAD

**Issue by Erazer750** [rre36/ShaderpackIssueTracker#22]
**Describe the bug**
Just as the title says: rain puddles do occur in hot bioms even though it doesn't rain there.
Ive mentioned this bug in your discord but for safety so you dont forget, I've made an issue report. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Enable the Kappa 4.0 Shader
2. Generate a hot biom like savanna/desert
3. Let it snow ... Ehm I mean rain or increase the humidity level
4. Watch the rain puddles and its lovley reflections

**Expected behaviour**
Rain puddles should not be produced in hot biom , because it never rains in those boims. At least in Minecraft it doesn't.

**Screenshots**
I might include some lovely screenies for you too

**Environment (please complete the following information):**
Irrelevant for this issue!

**Comment by rre36** [comment]
Fixed with 5.0
