### ISSUE TITLE
[Simplicissimus] More fog to cover the end of the render distance

### ISSUE THREAD

**Issue by seasonedfish** [rre36/ShaderpackIssueTracker#26]
Thanks for creating Simplicissimus shaders! I really love the shaderpack's clean look, especially in the Aether.
I have a feature request: more fog to cover the end of the render distance.

**Is your feature request related to a problem? Please describe.**
There isn't enough fog to cover the end of the render distance; the jagged chunk border lines are a bit jarring to see. This is especially noticeable [in the Nether](https://i.imgur.com/vzzoeAR.jpg).

**Describe the solution you'd like**
I don't know much about shaders, perhaps a higher cap for Fog Intensity in Shader Options?

**Comment by rre36** [comment]
Will be improved in 1.3
