### ISSUE TITLE
[PotatoShaders] Issue with enchantment shimmer

### ISSUE THREAD

**Issue by ghost** [rre36/ShaderpackIssueTracker#27]
**Describe the bug**
When enchanted objects are rendered, the item texture appears to be blacked out underneath the enchantment shimmer.
This applies to both carried items (Enchanted tools, written books, etc) as well as entities such as armor
-updated my graphics drivers
Still happening
-Rebooted my pc
Still happening

It is possible that this is a driver issue on my end? Nostalgia and vanilla+ render the shimmer just fine though.

**To Reproduce**
1) obtain enchanted item
2) equip
3) look at it

**Expected behavior**
When I carry an enchanted item, I would expect to see the Item's texture while the enchantment shimmer adds a bit of ~*Flair*~

**Screenshots**
https://imgur.com/a/q9ycGXD

**Environment (please complete the following information):**
Optifine Version: HD G7 Ultra
Minecraft Version: 1.16.5
Shaderpack Version: PotatoShaders v1.0
Graphics Card and Driver Version: Nvidia GeForce GTX 1060 3GB - GeForce game ready driver 466.27
Operating System: win10
CPU: Intel i7 4790
Amount of System Memory (total and assigned to Java): 8gig and idk

**Additional context**
[offtopic]
was kinda tired n' thought a skeleton was wearing netherite when it was probly wearing like leather or something lol
Absolutely loving the shader tho, Great work :)) makes me feel like I'm not a peasant

**Comment by rre36** [comment]
Already fixed in upcoming v1.1
