### ISSUE TITLE
Kappa v4.0, v4.1 E1 and PT P8 issue with HCM specular

### ISSUE THREAD

**Issue by hardtopnet** [rre36/ShaderpackIssueTracker#29]
You can see here the LabPBR hardcoded metal behavior is somewhat consistent across shaders
Continuum 2.1, Voyager 2.0, BSL v7.2 and v8.0, even Kappa v3.1 was displaying subtle golden specular highlights on my otherwise red albedo redstone (so its f0 is set at 231 AKA gold)

![output](https://user-images.githubusercontent.com/54667527/120322901-39536c80-c2e5-11eb-80f2-3870f2475029.gif)

since v4.0 and PT the gold completely overrides the albedo in most angles.

**Comment by rre36** [comment]
Fixed in past update
