### ISSUE TITLE
adjustable window for auto exposure

### ISSUE THREAD

**Issue by platyple** [rre36/ShaderpackIssueTracker#3]
when playing with kappa, i find it hard to see in environments with high contrast (i.e. any time you can see the world and sky at the same time), as the sky overpowers the screen's overall brightness, thus underexposing whatever you want to look at. 

the ideal solution would be a slider allowing you set the percentage/fraction of the screen around the crosshair that's put into calculating the average screen brightness. this is probably by no means realistic but nice to have for gameplay purposes.

depending on whether you're still using bloom tiles for autoexposure or not, using the middle 4 pixels of the nth mipmap (slider goes here) to get the overall screen brightness would be another option.

as for screenshots, kappa doesn't run on phones who cares anyways lol it's pretty self explanatory kthxbye

**Comment by rre36** [comment]
Fix is coming with version 4.0, including adjustable exposure weighting.
