### ISSUE TITLE
Any emissive item held in hand blinds the player, not playable in survival at night

### ISSUE THREAD

**Issue by hardtopnet** [rre36/ShaderpackIssueTracker#30]
**Describe the bug**
Any held emissive block will cause exposure to go bananas and completely blind the player which makes holding lanterns or such for survival exploration impossible. This happens with most Kappa shaders (also happens with Nostalgia to a lesser extent)

**To Reproduce**
1- load Kappa v3.0, v3.1, v4.0, v4.1, PT...
2- set time to midnight
3- without anything in hand, look around to check the overall exposure
4- put a sea lantern in hand
5- 
![image](https://user-images.githubusercontent.com/54667527/120323975-5d637d80-c2e6-11eb-95ab-44d00fdd517e.png)

**Expected behavior**
not 
![image](https://user-images.githubusercontent.com/54667527/120323988-60f70480-c2e6-11eb-9b11-3b571e9de184.png)

**Screenshots**

https://user-images.githubusercontent.com/54667527/120324007-681e1280-c2e6-11eb-92d8-0fd5a52e8eae.mp4

**Environment (please complete the following information):**
Optifine Version: OptiFine_1.16.5_HD_U_G8
Minecraft Version: 1.16.5 
Shaderpack Version: Kappa since v3.0
Graphics Card and Driver Version: nVidia GeForce RTX3080 
Operating System: Windows 10 2004 (19041)
CPU: MAD Ryzen 7 3700x
Amount of System Memory (total and assigned to Java): 64GB / 3GB to the Java machine

**Additional context**
If the UI and hand is hidden the issue goes away, which might indicate something to do with SSPT/SSGI or bloom

**Comment by OKTAYMERCAN** [comment]
That's true this exist on kappa 4.0, auto exposure settings killing atmosphere. Can't see anything. We are not camera device, make this like SEUS PTGI.

I leave example SS for this.

![2021-06-05_21 06 00](https://user-images.githubusercontent.com/20504071/120901177-f9241f00-c641-11eb-8b89-b4bee94aec4e.png)

**Comment by rre36** [comment]
Handheld emitters are indeed an issue currently, the general luminance range is not, which means that what is referred to in the second message is not an issue but intentional as is. The latter however is a matter of preference and can be adjusted in the settings.

**Comment by hardtopnet** [comment]
Tbh I feel this is more of a bugfix than an improvement, as it completely breaks survival gameplay.
Side note, if you manage to find an acceptable (and easy enough) solution, would you maybe backport it to 3.0/3.1? Those shader versions are different enough so that some people might prefer them (and they don't require latest Optifine changes so they're backward compatible with versions 1.14, 1.12 and possibly below).
They also might have slightly better performance so people with lower end specs might prefer them (not sure about this one though).

**Comment by OKTAYMERCAN** [comment]
Thanks for answer, this auto exposure correct ok, but contrast too much for gameplay. I try/test lots of different exposure, color etc. settings but still same :( can't see anything and can't playable.

![2021-06-06_01 36 09](https://user-images.githubusercontent.com/20504071/120907182-25eb2d00-c668-11eb-84f5-c5dd054e98d4.png)

and addionaly if I close volumetric fog under atmosphere tab, image will be foggy here is example

Volumetric fog: on

![2021-06-06_01 51 00](https://user-images.githubusercontent.com/20504071/120907411-c857e000-c669-11eb-8698-d5a522113d5f.png)

Volumetric fog: off

![2021-06-06_01 50 38](https://user-images.githubusercontent.com/20504071/120907420-e9b8cc00-c669-11eb-9f01-a26cd324b224.png)

I hope this problems fix on future updates, again thanks for answer.

**Comment by rre36** [comment]
You can raise the minimum ambient light to reduce the darkness relative to the emission, and the non-volumetric fog thing seems to be a bug.

**Comment by OKTAYMERCAN** [comment]
Thanks for the advice but I say I try lots of different settings. this include rise min ambient light too but still same result.

**Comment by rre36** [comment]
Resolved through various auto exposure and lighting changes coming with future updates.
