### ISSUE TITLE
fabric 

### ISSUE THREAD

**Issue by krispyking24** [rre36/ShaderpackIssueTracker#31]
can you please make a fabric port if there already is one can you link it

**Comment by frugbug** [comment]
shaderpacks aren't mods, they're loaded by mods. Optifine works on fabric via the Optifabric mod.

**Comment by krispyking24** [comment]
any way of running it without optifine on fabric with sodium?

**Comment by rre36** [comment]
You can wait until Iris actually works with my packs, however long that may take though but it works with Sodium at least (afaik).

**Comment by ruvaldak** [comment]
Iris 1.0.0 released 2 days ago but isn't near finished yet. Functional but no shader options yet, and none of rre's packs work yet. Just wait for Iris to reach feature parity.

**Comment by Mr-Waterscout** [comment]
You can use shader options with the starline fork of iris, found [here](https://github.com/HyperCubeMC/Iris), just go to the actions tab and find the downloads there
