### ISSUE TITLE
Replay mod - DOF

### ISSUE THREAD

**Issue by mathejka** [rre36/ShaderpackIssueTracker#32]
**Describe the bug**
When I shoot in a Replay mod and using DOF in the Kappa shader, it doesn't focus. For example, I am focusing on the grass but the grass is out of focus. When I'm in a normal world it focuses without a problem.

**Expected behavior**
When I'm in Replay and looking at a block, it should focus but it's blurred.

**Screenshots**
![out of focus2](https://user-images.githubusercontent.com/87401080/125544675-89f161a8-6175-4b36-993d-e8fad13774de.JPG)
![out of focus1](https://user-images.githubusercontent.com/87401080/125544677-015dd20f-a01d-4762-86b1-c4eef9d3cb1f.JPG)

**Environment (please complete the following information):**
Optifine Version: OptiFine_1.16.5_HD_U_G8
Minecraft Version: Forge 1.16.5 - 36.1.0
Shaderpack Version: Kappa_v4.0
Graphics Card and Driver Version: RTX 2070S / NVIDIA Studio Driver 461.92
Operating System: Windows 10 Pro
CPU: AMD Ryzen 7 3700x
Amount of System Memory (total and assigned to Java): 32GB RAM, 22GB RAM for Minecraft

**Additional context**

**Comment by AlejandroTheReal** [comment]
yo I had the same thing. I used Optifine and Optifabric but when I switched to Sodium and Iris mod than It worked

**Comment by rre36** [comment]
Issue is caused by replaymod seemingly overriding the center depth uniform used for depth of field
