### ISSUE TITLE
Waypoints of Journeymap doesn't show fine

### ISSUE THREAD

**Issue by rubensicko** [rre36/ShaderpackIssueTracker#33]
**Describe the bug**
The waypoints shows a black line.

**To Reproduce**
Create a waypoint

**Expected behavior**
It must show the waypoint color and info, distance, etc.

**Screenshots**
![bug](https://user-images.githubusercontent.com/75501780/135485810-841d7289-3499-4043-a6da-1d7b283b8c31.png)

**Environment (please complete the following information):**
Optifine Version: OptiFine-OptiFine-1.16.5_HD_U_G8_pre2.jar
Minecraft Version: 1.16.5
Shaderpack Version: Kappa_v4.1
Graphics Card and Driver Version: GTX 1660s
Operating System: Win10
CPU: i7
Amount of System Memory (total and assigned to Java): idk

**Comment by rre36** [comment]
Improper translucency rendering, issue caused by both the mod and optifine and very difficult to account for in a deferred shading pipeline.
