### ISSUE TITLE
Visual bug that I get with these shaders.

### ISSUE THREAD

**Issue by normie-chan** [rre36/ShaderpackIssueTracker#34]
**Describe the bug**
A very weird visual bug, I won't, be shocked if it's a settings issue I have that I just never knew about, still need help regardless, and it tends not to effect all of the shaders I use, cept this one and a few others.

**Expected behavior**
shadows? or at least darkness tends to spaz out while ingame

**Screenshots**
If applicable, add screenshots to help explain your problem. Preferrably with the F3 Screen being open.

**Environment (please complete the following information):**
Optifine Version:OptFine_HD_U_G9_pre33
Minecraft Version:1.17.1
Shaderpack Version:3.0
Graphics Card and Driver Version:1070 version "30.0.14.9613", least according to my device manager tab, while it says version 496.13 for my GeForce Experience tab. pretty sure they're the same for the fact they both have 49613 in them, but it's something I noticed nonetheless.
Operating System:Windows 10
CPU:"i7-8750H CPU @ 2.20GHz   2.21 GHz"
Amount of System Memory (total and assigned to Java): 4Gb

**Additional context**
weirdly when I go into face 3rd person everything is fine, cept everything else when I look around at the ground.
![Base Profile Screenshot 2021 10 15 - 15 35 04 29](https://user-images.githubusercontent.com/92609341/137561405-72c1823f-3fcc-4962-9fa8-e35926fdd132.png)
![Base Profile Screenshot 2021 10 15 - 15 42 08 39](https://user-images.githubusercontent.com/92609341/137561788-716cec09-0514-4ffb-b8ce-6465b34bba03.png)
![Base Profile Screenshot 2021 10 15 - 15 43 48 97](https://user-images.githubusercontent.com/92609341/137561900-cb58a957-1cea-4e66-8844-9a21e76fd6f8.png)
![Base Profile Screenshot 2021 10 15 - 15 44 08 09](https://user-images.githubusercontent.com/92609341/137561904-9c107c20-226b-4b14-b8fc-4b0289eccd35.png)

**Comment by rre36** [comment]
Cannot reproduce and got no other reports of this
