### ISSUE TITLE
Light being in a strong circle/square shape around a light source on reflective material

### ISSUE THREAD

**Issue by zoclhas** [rre36/ShaderpackIssueTracker#35]
**Describe the bug**
Light being in a strong circle/square shape around a light source on reflective material

**To Reproduce**
1. Enable a PBR pack
2. Use Kappa 4.1/KPT
3. build a flat area of iron/diamond/gold block
4. Place a light source like Sea lantern, a visible circular/square shape forms around it.

**Expected behavior**
A smooth (circular) light around the light source

**Screenshots**

![Java-runtime-alpha Screenshot 2021 10 18 - 18 42 43 74](https://user-images.githubusercontent.com/70476453/137756205-508a6134-0062-4032-9a5a-a21d627797ca.png)
![Java-runtime-alpha Screenshot 2021 10 
![Java-runtime-alpha Screenshot 2021 10 18 - 18 41 17 30](https://user-images.githubusercontent.com/70476453/137756189-35a6d3e5-d280-4a57-a25e-ff85e41b26c8.png)
18 - 18 40 55 48](https://user-images.githubusercontent.com/70476453/137756178-de9994d1-f1e6-410e-8753-d09edb25f126.png)

**Environment (please complete the following information):**
Optifine Version: 1.17.1 G9
Minecraft Version:1.17
Shaderpack Version:Kappa 4.1, KappaPT P9
Graphics Card and Driver Version: RTX 2060S, 
Operating System:Windows 10
CPU:Ryzen 5 3600
Amount of System Memory (total and assigned to Java): 16GB total, 4GB assigned 

**Additional context**
L4mbads pointed it out first, includes some of his aswell

**Comment by rre36** [comment]
Not a bug but a negative side effect of a compensation i added to prevent metals from turning fully black at night

**Comment by asadasadasads** [comment]
same happening here
