### ISSUE TITLE
Allow for transparent pixels to work

### ISSUE THREAD

**Issue by Justanidiotonline** [rre36/ShaderpackIssueTracker#36]
Basically, my skin has transparent pixels, they work with every other shader i have tried except this one, they just show up as hard white without the opacity. I'd like to see that added, because i feel like its missing.

Honestly just make this work with transparent pixels and you're golden
![2021-10-19_11 42 36](https://user-images.githubusercontent.com/50670501/137894190-cf4b7584-866f-45cd-8873-311b3fbe1186.png)

**Comment by rre36** [comment]
The player model is only rendered as a solid object, thus any kind of translucency is incompatible with a deferred shading pipeline like i use. This is more of an optifine/vanilla issue since the rendering order is what makes it impossible to handle a case like this correctly.
