### ISSUE TITLE
Buggy Water in Vanilla Plus

### ISSUE THREAD

**Issue by XenoxYT** [rre36/ShaderpackIssueTracker#37]
**Describe the bug**
There are no water waves like in the preview versions.

**To Reproduce**
1. enable custom water normals and color and then look at the water
**Expected behavior**

**Screenshots**
![2021-10-21_12 33 16](https://user-images.githubusercontent.com/78287711/138260891-8030501a-7f27-4d6a-98c8-6ad6e6765d19.png)

**Environment (please complete the following information):**
Optifine Version: 1.17.1 G9
Minecraft Version: 1.17.1
Shaderpack Version: 3.0 (even with 3.0a it doesn´t work. It worked in the preview versions)
Graphics Card and Driver Version: newest
Operating System: Windows 10 (Windows 11 not possible)
CPU: AMD Ryzen 2600X
Amount of System Memory (total and assigned to Java): Java 7GB and Total 16GB

**Additional context**

**Comment by rre36** [comment]
You need to enable reflections for custom water to fully work

**Comment by XenoxYT** [comment]
thx RRe36
