### ISSUE TITLE
Stop small amounts of water to continuously darken things behind them as if they are submerged in water

### ISSUE THREAD

**Issue by StarDDDude** [rre36/ShaderpackIssueTracker#38]
**Describe the bug**
When you have a thin wall of water and look through it, things which are far away will appear to be deep within water

**To Reproduce**
1. Open a World
2. Build a 1-Block Deep Waterlayer on a glass platform in the sky
3. Put some opaque blocks under one half of the platform
4. The Half with no Blocks directly beneath should appear significantly darker

**Expected behavior**
The expected result is for the water to only darken things by the amount of its thickness
So when water is set to darken things by 10% per block and you have 10 Block air gap between the water surface and rendered block, it should only darken the outcome by 10% instead of 100%

**Screenshots**
Here are a few examples using all the different shaders
Take into consideration that the left half of the surface is fully submerged in water beyond the glass

VanillaPlus (I added some dirt on the right to show the amount I'd expect the lower parts to have changed their color):
![Expected](https://user-images.githubusercontent.com/69975078/138340193-f9bf5a46-0715-4953-ba1f-c3e6269eb5bd.png)

UShader:
![UShder](https://user-images.githubusercontent.com/69975078/138339833-1bd82c35-2cde-4f6f-8d95-79c48b5318a8.png)

Simplissimus (even though this one is obvious):
![Simplissimus](https://user-images.githubusercontent.com/69975078/138339955-020eacb6-2b30-4eb6-a2ab-bceac6308203.png)

Kappa
![Kappa](https://user-images.githubusercontent.com/69975078/138340062-edd188ca-fc99-4837-93b6-ecbd58c8f7a9.png)

Take note that I have set the water density of the shaders as following:
Kappa: Density = 0.4
VanillaPlus: Falloff = 0.3
Simplissimus: Has none
UShader: Has none (I think)

Example Build using Kappa with 0.4 Density
![Example in Build 04](https://user-images.githubusercontent.com/69975078/138341944-231611c7-a7ef-4baf-910f-c98ecfecb8d0.png)

Example Build using Kappa with 1.0 Density
![Example in Build 10](https://user-images.githubusercontent.com/69975078/138342007-fdc2888e-cb46-4a72-b190-e11a22141380.png)

This does not happen for the standard shader, due to it only changing the lighting when entering the water:
(Simplissimus does not do the same from my testing)

![StandartTest](https://user-images.githubusercontent.com/69975078/138342321-09f1686a-db4b-4dce-9451-f94e538abd6d.png)

![StandartBuild](https://user-images.githubusercontent.com/69975078/138342306-475c207d-16dd-4c99-869a-bcf26bfd5f0d.png)

**Environment:**
Optifine Version: 1.17.1 HD U G9
Minecraft Version: 1.17.1
Shaderpack Version:
Kappa 4.1
Simplissimus 1.2
UShader 1.1
VanillaPlus 3.0
Graphics Card and Driver Version: Nvidia GeForce GTX 1050 Ti
Operating System: Windows
CPU: AMD Ryzen 5 3600X
Amount of System Memory (total and assigned to Java):
total: 16GB
java: I have no clue

**Extra info:**
For some reason the auto correct has recognized Kappa as being a word
Your shaders have gained the official recognition they deserve :kappa:

I know this should prolly be a feature request, but I realized too late
So enjoy the needlessly much info

**Comment by rre36** [comment]
This is unfortunately a technical limitation caused by optifine/minecraft itself as there currently isnt a way to get the location of the further water surface, so the best way is to just assume the depth of whatever **solid** object is behind it as where the water ends.
