### ISSUE TITLE
SSPT

### ISSUE THREAD

**Issue by tataranet0** [rre36/ShaderpackIssueTracker#39]
I really like this shader, i think it is the best ray tracing shader out there. But i have a question, it is possible to implemente a way to use the ray tracing option without the SSPT? In the inside of buildings is really annoying the fact that the light just disappears  when you don't look directly to a block that emit light. Sorry for the English errors, that's not my first language. Thank you for the incredible work, have a nice day :)

**Comment by gri573** [comment]
Hello,
There are multiple (two) path tracing shaders by rre36 that use voxelisation and hence don't strictly need screen space data for PT:
KappaPT ( [https://rre36.com/kappapt](https://rre36.com/kappapt) )
NostalgiaVX ( [https://rre36.com/nostalgiavx](https://rre36.com/nostalgiavx) )

There is technically also anglang, a WIP path tracing shader by rre36, niemand and jessie, but it isn't public yet, nor is there much information available about it.
