### ISSUE TITLE
OpenGL error message

### ISSUE THREAD

**Issue by iobiarg** [rre36/ShaderpackIssueTracker#4]
**Describe the bug**
There is OpenGL error (this is the only shader giving me that error and spamming my game chat)  "OpenGL error: 1282 (Invalid Operation)", I was having this issue with other shader, and the owner changed it from one day to the next one... 

**To Reproduce**
Happens randomly without specific action

**Expected behavior**
I was expecting not having that error message

**Screenshots**
<a href="https://ibb.co/fnZ95TN"><img src="https://i.ibb.co/QChkRxH/2021-02-13-03-36-05.png" alt="2021-02-13-03-36-05" border="0"></a>

**Environment (please complete the following information):**
Optifine Version: OptiFine_1.16.5_HD_U_G6
Minecraft Version: 1.16.5
Shaderpack Version: VPlus_v2.3a
Graphics Card and Driver Version: Evga GTX 1060 3GB driver game ready 461.40 updated two hours ago. Same happens with a msi gtx 560 ti
Operating System: Windows 10 Pro 64-bit
CPU: Intel Core i5 2500K @ 3.30GHz
Amount of System Memory (total and assigned to Java): 16,0GB Dual-Channel DDR3 @ 665MHz (9-9-9-24) and 14gb assigned to JAVA

**Additional context**
this is the only shader giving me this issue, but also the only one not giving me black/invisible entities

**Comment by rre36** [comment]
These OpenGL errors (namely 1281 and 1282) just randomly seem to happen with no direct cause. As long as you have no visual artifacts these can safely be ignored. If they annoy you they can also be surpressed in the Optifine settings but assuming these only randomly occur sometimes like they usually do it shouldn't be much of an issue.
