### ISSUE TITLE
maps in item frames

### ISSUE THREAD

**Issue by Kazm1um** [rre36/ShaderpackIssueTracker#40]
map textures are warped. they are also removed on the bottom half of the screen

1. place map in item frame
2. observe

**Expected behavior**
the maps look normal

![2021-11-03_09 16 40](https://user-images.githubusercontent.com/93662830/140077944-c1c8ccc8-ce3e-4b7a-b37c-273c6e877c1d.png)

Optifine Version: u g9 and newer
Minecraft Version: 1.17.1
Shaderpack Version: nostalgia vx p3b
Graphics Card and Driver Version: rtx 3070 driver version 496.49
Operating System: windows 11
CPU: amd 5600x
Amount of System Memory (total and assigned to Java): 32gb, 4gb

**Comment by rre36** [comment]
Issue is resolved with Iris and recent NostalgiaVX updates
