### ISSUE TITLE
Lighting problems

### ISSUE THREAD

**Issue by SuperVojtaz** [rre36/ShaderpackIssueTracker#42]
**Describe the bug**

**To Reproduce**
1. Go to any block and turn in any direction until you find artefacts.
2. See error

**Expected behavior**
Multiple instances of lighting artefacts and shadow glitches which cannot be fixed by changing settings

**Screenshots**
![2021-12-11_20 50 15](https://user-images.githubusercontent.com/91127016/145690296-6015a689-cb85-4026-a33a-4d71d48bd3b9.png)
![2021-12-11_20 54 07](https://user-images.githubusercontent.com/91127016/145690307-c8cef98d-2e95-45d7-b96d-061d1417724d.png)
![2021-12-11_20 54 14](https://user-images.githubusercontent.com/91127016/145690292-bc3ddf42-c3db-475f-a1aa-7aa5b45184e8.png)

**Environment (please complete the following information):**
Optifine Version: HD_U_G9
Minecraft Version: 1.17
Shaderpack Version: Kappa 4.1
Graphics Card and Driver Version: Aorus Master RTX 3080 10GB
Operating System: Windows 10 home 64 bit
CPU: Ryzen 7 5800X
Amount of System Memory (total and assigned to Java): 16Gb total, 2Gb assigned to java

Also keep in mind texturepack which can be seen on screenshots is reported to be fully functional with this shader

**Comment by frugbug** [comment]
Do you have Normal Map disabled in the shader selection screen? It needs to be enabled

**Comment by SuperVojtaz** [comment]
I love you, PBR finally works for me :DD
Also shadows are gone thanks!
