### ISSUE TITLE
 Incredible shadow breakage

### ISSUE THREAD

**Issue by SargRReal** [rre36/ShaderpackIssueTracker#44]
**Describe the bug**
Well the picture is pretty self explanatory, just enabled the shader and boom this.

With my specs i expected to run rather smoothly, but even on low settings the graphics are broken and my fps is down to 1.

Here's some screenshots
![2022-02-11_18 51 10](https://user-images.githubusercontent.com/78382320/153689377-cb3ea168-49da-4101-90dd-e31a3bd83ff1.png)
![2022-02-11_18 51 26](https://user-images.githubusercontent.com/78382320/153689380-c234a3a7-f4d7-4c44-b90b-063c57917701.png)

**Comment by SargRReal** [comment]
![2022-02-11_18 54 45](https://user-images.githubusercontent.com/78382320/153689418-2fa2d70d-dbd9-4b68-a693-4ffa2b63ed3b.png)

![2022-02-11_18 54 47](https://user-images.githubusercontent.com/78382320/153689420-dd460250-9ee1-4435-8389-a6df67827055.png)
here's a couple more

**Comment by rre36** [comment]
Try without mods, the performance is **waaaay** below whats normal (obviously) and those visual issues might be caused by a mod that interferes with the rendering.

**Comment by SargRReal** [comment]
> Owner

yeah i thought a mod could be an issue as well, but after removing all but optifine i still get the same results.
![2022-02-14_11 32 01](https://user-images.githubusercontent.com/78382320/153916090-7cb409d2-6911-4a06-abe4-ec1fc9b50511.png)
![2022-02-14_11 32 09](https://user-images.githubusercontent.com/78382320/153916095-5e1a7e74-b27e-4042-a261-2953b09327b3.png)
![2022-02-14_11 31 45](https://user-images.githubusercontent.com/78382320/153916099-11c0918d-931a-455f-8434-aebfa69d87c6.png)

**Comment by rre36** [comment]
Then try resetting video settings and make sure normals and specular maps are enabled in the optifine settings.

**Comment by SargRReal** [comment]
ok wow, it was having the normals disabled that broke everything. Now that it's enabled it's looking good now. Strange, but thank you:D
