### ISSUE TITLE
Shadow/Dark places are pink

### ISSUE THREAD

**Issue by FyrfyX8** [rre36/ShaderpackIssueTracker#45]
I Downloaded NostalgiaVX, and after loading the Shader, all Shadows or dark places glow pink
![image](https://user-images.githubusercontent.com/76538447/156181658-3a3e925b-bafc-44b3-9127-7c7c2698ad07.png)

Optifine Version: Optifine 1.18.1 HD U H4
Minecraft Version: 1.18.1
Shaderpack Version: NostalgiaVX_P6_2022-3-1
Graphics Card and Driver Version: NVIDIA GeForce RTX 3060 Ti/511.79
Operating System: Windows 11
CPU: AMD Ryzen 5 5600X
Amount of System Memory (total and assigned to Java): 32 GB RAM/16 GB Ram

**Comment by rre36** [comment]
Should no longer be an issue with recent updates
