### ISSUE TITLE
Noisy, blue fog that appears in caves (Nostalgia)

### ISSUE THREAD

**Issue by asadasadasads** [rre36/ShaderpackIssueTracker#47]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when Nostalgia's night fog doesn't look right in caves.

**Describe the solution you'd like**
Hm, I would really like to see some **noisy blue fog** in **caves** at night, that would look more cooler tbh
**Describe alternatives you've considered**
Maybe in the shader settings, in fog, it would be cool to see some noisy fog in caves, also can toggle it on and off.
**Additional context**
Fog like in the 1.18 trailer
![Fog](https://user-images.githubusercontent.com/100990848/156910546-caef4f6c-6a10-4caf-aec6-29df5832599d.png)
But with an slight noise, this would be an cool feature to be honest

**Comment by rre36** [comment]
Done for the next update, though the noise part isnt reasonable as I am using volumetric fog.
