### ISSUE TITLE
[Kappa, KappaPT] Water ontop of kelp gets default water texture

### ISSUE THREAD

**Issue by ThatOneCalculator** [rre36/ShaderpackIssueTracker#48]
**Describe the bug**
Water that appears on the surface that is directly above kelp gets the default water texture

**Screenshots**
![2022-03-12_12 00 32](https://user-images.githubusercontent.com/44733677/158033107-cb8e7e43-91f9-4595-bc0a-293e1512f768.png)

**Environment (please complete the following information):**
Optifine Version: 1.18.2 HD U H6
Minecraft Version: 1.18.2
Shaderpack Version: Kappa 4.1, KappaPT_PP14_2022-3-12_19.57
Graphics Card and Driver Version: Nvidia 2070 Super, 510.54
Operating System: Arch GNU/Linux
CPU: Ryzen 5800X
Amount of System Memory (total and assigned to Java): 32GB total, 8GB to Minecraft

**Additional context**

- This is on a public MC server
- Westera 2.1 Resource Pack

**Comment by Reeses-Puffs** [comment]
this is a known bug and is not the fault of the shader. please wait for the optifine developer to fix this.

**Comment by ThatOneCalculator** [comment]
Gotcha. Thank you for letting me know :)
