### ISSUE TITLE
Background flashing when sweeping mobs with sword/mostly when background is sky or moon during night

### ISSUE THREAD

**Issue by bediisin1001** [rre36/ShaderpackIssueTracker#49]
**Describe the bug**
The flashing animation when hitting a mob with the sweep attack(sword) makes a light orange flash that affects also the far background of the world and makes it look more foggy and unnatural. My settings are default. I mostly notice it during night and attacking for example zombies. It mostly happens when the clear sky or moon is in the background.

**To Reproduce**
4. See error(I hope I wrote everything)...
![2022-03-14_21 37 07](https://user-images.githubusercontent.com/101599036/158257272-89fb6b08-011f-4f53-9226-3e69b00918e2.png)
![2022-03-14_21 24 48](https://user-images.githubusercontent.com/101599036/158257304-92fac22a-cdaa-4869-9a3f-232423326059.png)

**Expected behavior**
Normally I would expect that the background wouldn´t flash in a bright cololr tone when using the sweep attack with the sword against mobs. It mostly happens when the background is a bright spot like the night sky or moon. I only notice it during night time.

**Screenshots**
If applicable, add screenshots to help explain your problem. Preferrably with the F3 Screen being open.

**Environment (please complete the following information):**
Optifine Version: Optifine 1.18.2 HD U H6
Minecraft Version: 1.18.2
Shaderpack Version: [Kappa_v4.2_T2.zip]
Graphics Card and Driver Version: 511.79
Operating System: Windows 10
CPU: i5-12600K
![2022-03-14_21 24 48](https://user-images.githubusercontent.com/101599036/158255582-ee28d4fc-6661-4d0e-b59e-d05a7a66c8f3.png)

Amount of System Memory (total and assigned to Java): 32GB / 4GB allocated

**Additional context**
It looks like the whole background of the world gets affected by this animation/flash and makes it seem more foggy and bright.. which during night looks very unnatural.

**Comment by bediisin1001** [comment]
It kinda looks similar like the background lighting from Glowstone or other bright blocks.. still looks a bit weird.. especially with the sword sweeping animation(ofc if no optifine issue).
![2022-03-14_22 09 22](https://user-images.githubusercontent.com/101599036/158263578-9781ba38-f000-4e04-b650-b1ff00065d2f.png)

**Comment by rre36** [comment]
This is caused by particles being rendered as fullbright by the vanilla rendering
