### ISSUE TITLE
Invalid program "composite12", world is comlpetely black.

### ISSUE THREAD

**Issue by infradragon** [rre36/ShaderpackIssueTracker#5]
Specs: RX 580, Linux Mint 64 bit, OptiFine HD U G7 pre9.
When i load the shaders, it gives me three errors:

`17:42:08.028
net.optifine.shaders.SMCLog
main
[Shaders] OpenGL error: 1282 (Invalid operation), program: composite12, at: useProgram

17:42:08.029
net.optifine.shaders.SMCLog
main
[Shaders] [Shaders] Error: Invalid program "composite12"

17:42:11.196
net.optifine.shaders.SMCLog
main
[Shaders] Error compiling fragment shader: /shaders/world0/composite12.fsh
`

Clearly, there is something wrong with /world0/composite12.fsh
when i open composite12.fsh, it leads me to shaders/program/grading.fsh
**grading.fsh (which controls ACES)  will not run, and makes the shaders unusable**

**Comment by infradragon** [comment]
This is for Kappa Shaders v3.1a, btw

**Comment by rre36** [comment]
This is a driver specific issue with the Mesa drivers as optifine does not detect them as "GL_RENDERER_MESA" since Mesa 21. Workaround fix is on its way.
