### ISSUE TITLE
it does not matter if im using newer versions of optifine or not

### ISSUE THREAD

**Issue by greninja29011** [rre36/ShaderpackIssueTracker#51]
**Describe the bug**
the rain is blinding and the clouds make it normal, while the glitch is more noticable at night.
**To Reproduce**
it does not matter how it happens, even when i first downloaded it, it just happened
**Expected behavior**
i expected it to work like every other shader, its just the rain not the clouds, not the ground, the rain.
**Screenshots**
![help](https://user-images.githubusercontent.com/84482900/160217593-c0301f7c-2771-41e9-bfb7-a9a7b0b22185.png)

**Environment (please complete the following information):**
Optifine Version: 1.17.1_HD_U_G9
Minecraft Version: 1.17.1
Shaderpack Version: Ushaders v1.1
Graphics Card and Driver Version: GTX 1660
Operating System: aSUS gaming laptop
CPU: AMD Ryzen 7
Amount of System Memory (total and assigned to Java): 425gb 80gb

**Additional context**
it only happens for Ushaders

**Comment by rre36** [comment]
UShader isn't currently made for newer versions of Minecraft (eg. 1.15 and newer), thus these issues are expected.
Obviously already fixed in the upcoming 2.0.
