### ISSUE TITLE
Cave Lightning issue with Vanilla Plus shaders

### ISSUE THREAD

**Issue by Binekrasik** [rre36/ShaderpackIssueTracker#52]
**Describe the bug**
When i go to the cave i see these weird lights at edges of blocks. 

**To Reproduce**
1. Go to any world or server
2. Go to any cave
3. Be sure it's day
4. You will se weird lightnings at the edges of blocks

**Expected behavior**
There will be normal, dark light of cave at any block.

**Screenshots**
![image](https://user-images.githubusercontent.com/66784259/160608493-1e45ff9b-eec8-4ff7-bc6d-3105e7163399.png)

**Environment (please complete the following information):**
Optifine Version: 1.18.2 HD U H6
Minecraft Version: 1.18.2 Lunar Client
Shaderpack Version: Vanilla Plus 3.0b (and older)
Graphics Card and Driver Version: AMD Radeon RX 5500 XT, Driver: 30.0.14029.5006
Operating System: Windows 10 Home
CPU: AMD Ryzen 5 3600  6 Cores
Amount of System Memory (total and assigned to Java): Total 16GB, Java 8.6GB

**Additional context**
Idk if it's happening only to me.

*Yes, i know, my english is bad.*

**Comment by rre36** [comment]
Ordinary lightleaking, enable the lightleak workaround in the latest update or complain to optifine.
