### ISSUE TITLE
Modded lights compat.

### ISSUE THREAD

**Issue by ShibeTemple** [rre36/ShaderpackIssueTracker#53]
Hello! I was wondering, for NostalgiaVX if it is possible to add support for modded light sources? All of them seem to have no emissive light.

**Comment by Reeses-Puffs** [comment]
It would be tedious to add support for every block in every mod so that they're lit correctly. Your best bet is waiting for Focal Engine.

**Comment by ShibeTemple** [comment]
> It would be tedious to add support for every block in every mod so that they're lit correctly. Your best bet is waiting for Focal Engine.

I don't understand this notion. Why can there not be a default value? Other shaders do this successfully. Identify it's a light source, then emit a standard color if not preset.

**Comment by Reeses-Puffs** [comment]
Other shaders do this successfully because they don't use the advanced lighting system that NostalgiaVX uses. To add support for modded blocks would you literally have to add each block and what type of block it is by hand into whichever program voxelizes the world. Focal Engine isn't going to remedy this completely, but it will make mod compatibility much easier.

**Comment by ShibeTemple** [comment]
> Other shaders do this successfully because they don't use the advanced lighting system that NostalgiaVX uses. To add support for modded blocks would you literally have to add each block and what type of block it is by hand into whichever program voxelizes the world. Focal Engine isn't going to remedy this completely, but it will make mod compatibility much easier. 

Does the shader program not pass the light output of a block? There could be a default handler in the voxel-based method.

**Comment by rre36** [comment]
The issue is that NostalgiaVX does not use the vanilla lightmap at all in favour of the much higher quality lighting using voxels and path-tracing. This is why manual mapping is necessary atm, since there is no way for it to reliably detect emitters otherwise for now.
