### ISSUE TITLE
Weird Bloom effect on block selection outline and on enderman while in nether and end dimension 

### ISSUE THREAD

**Issue by Noodleship** [rre36/ShaderpackIssueTracker#54]
There is a weird effect in the Kappa Shader that happens when putting your crosshair on a block while in the nether or the end. Parts of the enderman texture also glow for some reason only in the nether and the end. Everything in the overworld seems to look normal.

**To Reproduce**
1. Go to the nether or end
2. Put cross hair onto a block or spawn an enderman

**Expected behavior**
There should be no glowing effect.

**Screenshots**
https://imgur.com/a/Qpn3rEB

https://imgur.com/a/hc8e931

https://imgur.com/a/LmL1uRM
(Turned off the bloom effect to see enderman texture)

https://imgur.com/a/yFkKQwt
(no issues in the overworld)

Optifine Version: 1.18.2 HD U H7
Minecraft Version: 1.18.2
Shaderpack Version: Kappa_v4.2
Graphics Card and Driver Version: Nvidia Quadro p2000   Driver Version 512.15
Operating System: Windows 10
CPU: Intel(R) Xeon(R) Silver 4108 CPU @ 1.80GHz
Amount of System Memory: 32gb total and 2gb assigned to Minecraft Java

**Comment by rre36** [comment]
Known driver issue with nVidia Quadro GPUs
