### ISSUE TITLE
Chinese language file

### ISSUE THREAD

**Issue by FlyModeZ** [rre36/ShaderpackIssueTracker#55]
I made a chinese language file for the Nostalgia Shader.
[zh_cn.lang.txt](https://github.com/rre36/ShaderpackIssueTracker/files/12184474/zh_cn.lang.txt)

**Comment by rre36** [comment]
Unfortunately settings files tend to become outdated after major/sweeping changes due to changing internal settings values and parameters and I can't maintain them, hence this unfortunately never made it into a release version.
