### ISSUE TITLE
Visual Glitches [Kappa]

### ISSUE THREAD

**Issue by SweatoPants** [rre36/ShaderpackIssueTracker#57]
**Description**
--Shadow Visual Glitch--
player shadow artifacts on pbr textures.

--Item Visual Glitch--

hand held items leave an after image if the screen moves fast enough or the item is swung.

**Reproduce**
--Shadow--
Enable PBR look at the ground while moving.

--Item--
No idea it just happens, easiest to notice with enchanted tools being swung over stone blocks
Expected:
the player shadow to not have any artifacts within block textures

**Screenshots**
--shadow--
![2022-05-15_13 33 48](https://user-images.githubusercontent.com/99714225/168488509-8c9f8119-9650-4fed-a734-78217c65fa14.png)

--item--
![2022-05-15_13 45 51](https://user-images.githubusercontent.com/99714225/168488952-854e4b90-b147-49d4-8fb9-50d424c16b8c.png)

![2022-05-15_13 44 57](https://user-images.githubusercontent.com/99714225/168488934-875956ba-a11d-4899-985c-eca63a434f3d.png)

**Environment (please complete the following information):**
Optifine Version: OptiFine_1.18.2_HD_U_H7
Minecraft Version: 1.18.2
Shaderpack Version: 4.2
Graphics Card and Driver Version: GTX 1060 6GB | 512.59
Operating System: Windows 11
CPU: i7-8700 3.70GHZ
Amount of System Memory (total and assigned to Java): 16GB | 6GB

**Additional**

This happens outside the modded client aswell, none of the mods effect the image, only minimap, item displays, jei, worldedit

**Comment by rre36** [comment]
Thats just an artifact caused by the temporal anti-aliasing, not really a bug but rather just a shortcoming of the current implementation
