### ISSUE TITLE
Skin Translucency Issue (Bug or something else?)

### ISSUE THREAD

**Issue by Gadg3tguy** [rre36/ShaderpackIssueTracker#58]
When using the Vanilla + shader with Optifine on Minecraft 1.18.2, the translucent layer on my skin is opaqe.

**Screenshots**
![2022-06-11_14 04 10](https://user-images.githubusercontent.com/107320458/173199840-82d4493c-eb7a-4daa-b696-748e3d7eaebc.png)
![2022-06-11_14 03 39](https://user-images.githubusercontent.com/107320458/173199841-893c39c0-162b-4838-9e07-079b72c4ba51.png)

Optifine Version: OptiFine_1.18.2_HD_U_H7
Minecraft Version: 1.18.2
Shaderpack Version: VanillaPlus_v3.0a
Graphics Card and Driver Version: Radeon RX 570, Driver Version
21.50.02.01-220309a-377495C-AMD-Software-Adrenalin-Edition
Operating System: Windows
CPU: AMD Ryzen 5 2600X Six-Core Processor              3.60 GHz
Amount of System Memory (total and assigned to Java): 32 GB, 12 GB

**Comment by rre36** [comment]
This has been fixed in 3.0b
