### ISSUE TITLE
Visual Errors with Kappa Shaders v4.2

### ISSUE THREAD

**Issue by DomQuantum** [rre36/ShaderpackIssueTracker#59]
**Describe the bug**
The issues experienced seem to be related to the lighting or shadows controlled by the shader pack. In addition just an image file for the sky.

(1) Items in player hand become semi-translucent and grainy. This appears to be happening due to the shadows from the lighting or sunlight. The shadows being cast have a similar effect  when looking at the shadows so I believe its this that is overlapping with items in the players hand, causing a translucent grainy effect on those items.

(2) Concerning the maps, Maps that are facing the sun are not legible, They appear to be dark, shadowed or under shadow. However when they are placed facing other directions, they can be clearly seen. It can also be seen that when placing a map down that is facing the sun, it goes down visible but fades into darkness making it hard to read.

(3) The horizon for the sky is a bit off putting, this isn't so much an error as is it general feedback. In some lighting conditions it appears very harsh and it an eyesore. It may just be better to create a better fade in the sky so that the horizon isn't as sharp or clearly identified. When flying in the sky, the horizon line appears to be higher too making the cut of from the render distance and the horizon wider and visually annoying. There just always appears to be a large gap between the land and the sky.

**To Reproduce**
1. Load shaders
2. Place a map on a wall facing the sun.
3. See error
4. Hold an item in player hand and walk through shadows being cast
5. See error
6. Look at sky horizon
7. See error

**Expected behavior**
(1) shadows should not be making held items grainy and transparent.

(2) maps should be visible and readable if facing the sun.

(3) the horizon should be easier on the eyes visually instead of it being a harsh contrast. 

**Screenshots**
(1) ![2022-07-08_12 54 52](https://user-images.githubusercontent.com/25904354/178041371-b8d5c14c-f6f1-4648-b380-721b13dd4e6a.png)

(2) ![2022-07-08_12 55 38](https://user-images.githubusercontent.com/25904354/178037467-a8233c51-5697-46d8-862e-22b33228391b.png)

(3) ![2022-07-08_12 56 18](https://user-images.githubusercontent.com/25904354/178037361-680ed7fa-1c2c-4338-90b2-1403d320bb27.png)

**Environment (please complete the following information):**
Optifine Version: preview_OptiFine_1.19-HD_U_H8_pre8.jar
Minecraft Version: 1.19
Shaderpack Version: 4.2
Graphics Card and Driver Version: 2080TI 11GB
Operating System: Windows10
CPU: Intel9-9900k
Amount of System Memory (total and assigned to Java): 12GB

**Additional context**
Love the shaders, would love to see if improve further

**Comment by rre36** [comment]
(1) Thats a side effect of temporal dithering to smooth various effects, intentional and not a bug, just overly visible there
(2) This issue is caused by incorrect vertex data provided by optifine
(3) The horizon behaviour can be changed since 5.0
