### ISSUE TITLE
Dynamic Surroundings Compatibility

### ISSUE THREAD

**Issue by whitefire89** [rre36/ShaderpackIssueTracker#6]
**Is your feature request related to a problem? Please describe.**

This has to do with transparency problems with combining it with dynamic surroundings.  The opacity of all effects from the mod are all the way up.  I'd like to have a shader pack that doesn't do this to Dynamic Surroundings.

**Describe the solution you'd like**

I really like the Vanilla Plus shader pack, however, I can't help but think the opacity issues with Dynamic Surroundings are something that the shader pack makers have to work out and maybe work together with OreCrucher (maker of Dynamic Surroundings) with.  Every single effect from DS is at full opacity when shaders are turned on.

**Describe alternatives you've considered**
I don't think there's an alternative to this.  There's nothing in any of the settings for any shader pack that allow effect transparency manipulation.

**Additional context**

**Comment by rre36** [comment]
Certainly something I have looked into in the past, but compatibility with optifine/shaderpacks is a bit of a tricky thing to get working as these environmental effects should ideally have their own pass to be rendered properly in the pipeline instead of being rendered together with (and thus as) solid objects.

**Comment by whitefire89** [comment]
So, the way I understand it (and I don't know anything about making shader packs), the effects, one at a time, have to be given their own flag to allow them to bypass being rendered like everything else?

**Comment by rre36** [comment]
Well ideally all the translucent effects would be rendered in a dedicated pass so that they can be stored separately and then applied whenever its best for the shaderpack to do so.

**Comment by rre36** [comment]
Should be resolved with Iris and potentially also recent Optifine versions
