### ISSUE TITLE
Let there be light... NOT

### ISSUE THREAD

**Issue by Nabroc** [rre36/ShaderpackIssueTracker#61]
I'm using NostalgiaVX with the Patrix resource pack in 1.16.5 and there doesn't seem to be any light emitting from torches.

![image](https://user-images.githubusercontent.com/110527304/182790242-a5d46dbb-f063-40fc-8b91-76a932903e7e.png)

**Comment by Reeses-Puffs** [comment]
NostalgiaVX does not have dynamic lights, and will not for the foreseeable future.
