### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by NoahTheNerd** [rre36/ShaderpackIssueTracker#63]
Whenever I enable Kappa on any version, my screen is black, I have the issue with Iris and Optifine.
Using EVGA RTX 3050 GPU

Screenshots:
![2022-11-24_10 24 33](https://user-images.githubusercontent.com/79805455/203847617-d2c267e1-e877-4ef2-8cae-ed0acaddebe2.png)
![2022-11-24_10 24 35](https://user-images.githubusercontent.com/79805455/203847627-68d5278f-9c11-407b-8812-c4b5834ee6fc.png)

**Comment by rre36** [comment]
Got no other reports of this and the issue is not reproducable on my end.
