### ISSUE TITLE
Soft Voxels 1.0a water glitch

### ISSUE THREAD

**Issue by TheBeautyLlama** [rre36/ShaderpackIssueTracker#65]
**bug**
visual glitch on water

**reproduce**
start the game

**Expected behavior**
working water :D

**Screenshots**
If applicable, add screenshots to help explain your problem. Preferrably with the F3 Screen being open.

![2022-12-21_19 12 34](https://user-images.githubusercontent.com/84794955/208867260-d7fbd2fb-9875-46a6-82e0-2ffe1ae63159.png)

![2022-12-21_19 11 56](https://user-images.githubusercontent.com/84794955/208867223-bde5c18f-ca12-42b0-92e4-be211d0e0068.png)

**Environment (please complete the following information):**
Optifine Version: I1_pre4
Minecraft Version: 1.19.2

Shaderpack Version: Soft Voxels 1.0a
Graphics Card and Driver Version:  680m, driver in f3 menu
Operating System: win11
CPU: R7 6800H
Amount of System Memory (total and assigned to Java): 16G, assigned 1512MB

**Comment by rre36** [comment]
Not a shaderpack bug, most likely caused by incorrect settings, drivers or OptiFine.
