### ISSUE TITLE
Always night

### ISSUE THREAD

**Issue by Waffles3438** [rre36/ShaderpackIssueTracker#66]
**Describe the bug**
Sky is always dark

**Expected behavior**
For day to be bright

**Screenshots**
![2022-12-30_10 15 29](https://user-images.githubusercontent.com/96705793/210085563-09190f68-4e58-420b-b3d5-8c7831616f28.png)

**Environment (please complete the following information):**
Minecraft Version: 1.19.2
Shaderpack Version: v3.0b
Graphics Card and Driver Version: 527.56
Operating System: W10
CPU: R5 5600X
Amount of System Memory (total and assigned to Java): total: 16gb assigned to java: 2gb

**Comment by rre36** [comment]
Update to Iris 1.5.0 or newer.
