### ISSUE TITLE
Shader Error

### ISSUE THREAD

**Issue by mrdiamondmanguydudeman** [rre36/ShaderpackIssueTracker#67]
**Describe the bug*
It just crashes when I apply the Shader
**To Reproduce**
1. Go to download Oculus, the Forge fork of Iris
2. Click on 'Kappa'
3. Scroll down to 'Apply'
4. Crashes
5. See error

**Expected behavior**
I though it was going to load?

**Screenshots**
If applicable, add screenshots to help explain your problem. Preferrably with the F3 Screen being open.

**Environment (please complete the following information):**
Oculus Version: 1.2.8
Forge Version: 43.1.52
Minecraft Version:1.19.2
Shaderpack Version:5.0
Graphics Card and Driver Version:Idk, Radeon?
Operating System:Windows 10
CPU:idk
Amount of System Memory (total and assigned to Java):about 6 or 7 I dont remember

**Additional context**
here is the error log:  https://pastebin.com/iEagmQpR

**Comment by ciaens** [comment]
Occulus just doesn't support rre36's shaders. You have to use optifine or Iris.

**Comment by mrdiamondmanguydudeman** [comment]
Ah ok, Thank you for telling me.
