### ISSUE TITLE
Will UShader 2.0 be compatible with Iris?

### ISSUE THREAD

**Issue by TheD0ct0r101** [rre36/ShaderpackIssueTracker#68]
Currently, UShader 2.0 yields a white screen when you attempt to use it with Iris (which runs significantly better than Optifine.)

I was curious if this is something on UShader's end or if it's a fault of Iris's current state. If its the latter I could make a post on their end requesting compatibility.

**Comment by ciaens** [comment]
Just update iris.

**Comment by TheD0ct0r101** [comment]
> 

Dang, wasn't aware they pushed a decently sized update. Seems to have done the trick though, nice and easy. Thanks!
