### ISSUE TITLE
All light disappear when looking straight up

### ISSUE THREAD

**Issue by Gurkanan** [rre36/ShaderpackIssueTracker#7]
Both me and a friend have this issue while playing on a skyblock modpack. And night time looks like daytime unless i look straight up into the sky. Stars still appears during night time and not during the day.

Game info:
Shaders Kappa v3.1a
Minecraft version: 1.16.4
Forge: 35.1.37
Optifine: HD G7 Ultra
Modpack: Sky Bees

My specs:
OS: Windows 10 20H2
CPU: Intel core i5 4690K overclocked
GPU: RTX 3070

**Comment by rre36** [comment]
This seems like some mod is interfering with the sky rendering. Not sure if there's a workaround for it but could you try splitting the mods into two groups and then rinse repeat with the group that has the issue to find out which mod causes it?

**Comment by Gurkanan** [comment]
i think its astral sorcery. How ever i have seen that other shaderpacks have a dark night setting which seems to work. Sildurs to be specific.
SEUS renewed also dont have any night issues.
