### ISSUE TITLE
SoftVoxels error: Invalid program "deferred 2/5"

### ISSUE THREAD

**Issue by xdZronz** [rre36/ShaderpackIssueTracker#70]
**Describe the bug**
When ever I select the shader I get the error Error: Invalid program "deferred 2" and Error: Invalid program "deferred 5" in chat.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Preferrably with the F3 Screen being open.
![2023-01-23_14 57 25](https://user-images.githubusercontent.com/93431260/214060568-6fc1d5d8-1add-4088-9a9f-83f53b304778.png)

**Environment (please complete the following information):**
Optifine Version: 1.19.2_HD_U_H9
Minecraft Version: 1.19.2
Shaderpack Version: 
Graphics Card and Driver Version: RTX 3060, 528.02
Operating System: Win 11 
CPU: AMD Ryzen 5600x
Amount of System Memory (total and assigned to Java): 16GB, 3GB assigned to Minecraft

**Additional context**

**Comment by rre36** [comment]
Soft Voxels P6 and newer do not support OptiFine anymore. Use Iris 1.5.0 or newer instead.
