### ISSUE TITLE
Vanilla plus error

### ISSUE THREAD

**Issue by mrdiamondmanguydudeman** [rre36/ShaderpackIssueTracker#71]
**Describe the bug**

**To Reproduce**
1. Go to 'Shader Packs'
2. Click on 'Vanilla Plus'
3. Profit

**Expected behavior**
I thought It would load

**Screenshots**
If applicable, add screenshots to help explain your problem. Preferrably with the F3 Screen being open.

**Environment (please complete the following information):**
Iris Version: 1.2.7
Minecraft Version: 1.17.1
Shaderpack Version:
Graphics Card and Driver Version:idk
Operating System: Radeon
CPU:idk
Amount of System Memory (total and assigned to Java): 2G

**Comment by rre36** [comment]
Iris 1.5.0 or newer is required, older versions are not supported.

**Comment by mrdiamondmanguydudeman** [comment]
Thanks!
