### ISSUE TITLE
SoftVoxels_p6c Refuses to work under any circumstances in this instance

### ISSUE THREAD

**Issue by OsumaKisoku** [rre36/ShaderpackIssueTracker#72]
All blocks are black but lights show up, there is a difference in-between profiles normal, and quality, quality shows the lights, normal has a black roof over my head. 
![2023-01-30_14 54 43](https://user-images.githubusercontent.com/124003849/215615856-68c1c9cc-e504-4145-85a9-6e2967441c80.png)
![2023-01-30_14 55 07](https://user-images.githubusercontent.com/124003849/215615873-5c7e87d2-6615-473e-a7bd-3b3198cd78f4.png)

**Comment by OsumaKisoku** [comment]
I am running a 
3060, I9-11900k, 64GB DDR4 3200MHZ (Minecraft is limited to 12 Gigs of Ram)

**Comment by ciaens** [comment]
Use iris. Optifine isn't supported anymore as it lacks features only iris have.

**Comment by rre36** [comment]
Iris 1.5.0 or newer specifically
