### ISSUE TITLE
 Underwater blocks display incorrectly

### ISSUE THREAD

**Issue by TeaCupTwe** [rre36/ShaderpackIssueTracker#73]
**Describe the bug**
Stained glass, slime blocks, honey blocks, etc. in water do not display correctly
![image](https://user-images.githubusercontent.com/124753793/217419217-100a5eb9-323f-42a6-9f75-a49034ef37f9.png)
**To Reproduce**
Put the glass in the water, people also go into the water, maybe BUG will appear
Environment (please complete the following information):
Optifine Version: OptiFine HD U I2 pre3
Minecraft Version: 1.19.3

**Comment by rre36** [comment]
Should be fixed in upcoming updates across any of my packs with this issue.
