### ISSUE TITLE
Add translucent entities support

### ISSUE THREAD

**Issue by Lolothepro** [rre36/ShaderpackIssueTracker#74]
**Screenshots**

![2023-03-21_19 35 43](https://user-images.githubusercontent.com/68275908/226708431-7ff7b58e-6432-4fec-91bc-24fc73ca4ce6.png)

**Comment by rre36** [comment]
This requires changes on the side of Iris/OptiFine due to rendering limitations in the current pipeline.

**Comment by Lolothepro** [comment]
oh
