### ISSUE TITLE
Light leaking from block borders

### ISSUE THREAD

**Issue by BigJeremy** [rre36/ShaderpackIssueTracker#76]
I have a bug with the newest version of Vanilla Plus Shaders.
As seen on the pictures I have light leaking from block borders when I am in a cave.
I'm using the Lightleak Preventation but the bug still happens.
I've tried changing every setting but I can't get this to work.

**To Reproduce**
1. Use VanillaPlus _v3.0b shaders
2. Go to a cave during the day
3. Light leaks from block borders

**Expected behavior**
I expect the Lightleak preventation setting should fix this issue.

**Screenshots**
![2023-04-12_23 54 14](https://user-images.githubusercontent.com/130611959/231598570-0f732583-4fb5-4e6e-86c8-78d952298227.png)
![2023-04-13_00 11 21](https://user-images.githubusercontent.com/130611959/231598594-1c045aa5-738f-4f1e-9ee0-6a656f33f4cf.png)

**Environment (please complete the following information):**
Optifine Version: 1.19.4-OptiFine_HD_U_I3
Minecraft Version: 1.19.4
Shaderpack Version: VanillaPlus _v3.0b
Graphics Card and Driver Version: RTX 2080TI, 531.41
Operating System: Windows 10 PRO
CPU: AMD Ryzen 7 5800x
Amount of System Memory (total and assigned to Java): 32gb (IDK about Java)

**Additional context**
Please help :(

**EDIT**
I also tried it with 1.19.2 version of optifine and minecraft.
The same thing still happened.

**Comment by Voidatron** [comment]
This is happening to me too

**Comment by rre36** [comment]
the lightleak prevention doesnt work when there is too much skylight present, as it is in your first image
