### ISSUE TITLE
Shader pack messes with particle transparency

### ISSUE THREAD

**Issue by IFOZVORTEX** [rre36/ShaderpackIssueTracker#77]
**Describe the bug**
Particle messes with mods particle transparency, otherwise working fine
ALTHOUGH for Astral sorcery, if i join with the shader already activated the particle are all black, and if i change the shader mid-game, there are "normal" but still without transparency, as for other mods like blood magic, if i join with the shader already activated, everything is normal, if i change mid-game, the blocks lose their textures

**To Reproduce**
just launch the game with the shaderpack on, or change the shaderpack mid-game

**Expected behavior**
Particles transparency and colors expected to be rendered correctly

**Screenshots**
If applicable, add screenshots to help explain your problem. Preferrably with the F3 Screen being open.
shader preloaded
astral sorcery example
![2023-05-14_16 29 49](https://github.com/rre36/ShaderpackIssueTracker/assets/60710198/f4be5303-4837-4ac8-812f-7bf260071b4c)

shader changed mid-game
astral sorcery example
![2023-05-14_16 34 49](https://github.com/rre36/ShaderpackIssueTracker/assets/60710198/dfca04c4-e93f-4585-b90f-845ffb114827)

**Environment (please complete the following information):**
Optifine Version: dunno tbh
Minecraft Version: 1.16.5
Shaderpack Version: 3.0a
Graphics Card and Driver Version: Nvidia geforce gtx 950
Operating System: windows 10
CPU:
Amount of System Memory (total and assigned to Java): 16Gb and i think more than 4Gb assigned to java

**Additional context**
couldn't get the blood magic texture bug to reoccur, but it just replaces the block with the pink and black squares textures

**Comment by IFOZVORTEX** [comment]
also i forgor my cpu it is a intel core i5-6400

**Comment by rre36** [comment]
this is caused by incorrect particle rendering by astral sorcery/optifine, where particles are being rendered in a pass that is only supposed to render solid objects without translucency
