### ISSUE TITLE
Nostalgia/Kappa/etc. shader's TAA causes significant flickering when viewing smooth snow layers 

### ISSUE THREAD

**Issue by Creare-d-arte** [rre36/ShaderpackIssueTracker#78]
**Describe the bug**
In scenes, like that shown in the attached screenshot, the shader's TAA causes significant flickering.

Checkout this link for reference: https://forum.unity.com/threads/taa-medium-long-distance-issue-flickering.1222215/

**To Reproduce**
1. Create a landscape using snow layers.
2. Turn on/enable Nostalgia, Kappa, etc. shaders.
3. View visible flickering.

**Expected behavior**
As visual quality is significantly impaired when flickering is present; there should be little to no flickering on screen. 

**Screenshots**
https://imgur.com/a/65M8PVV

**Environment (please complete the following information):**
Iris Version: 1.6.2 for 1.19.2
Minecraft Version: 1.19.2
Shaderpack Version: Any version
Graphics Card and Driver Version: Nvidia RTX 3080, latest driver
Operating System: Win11
CPU: AMD Ryzen 5800
Amount of System Memory (total and assigned to Java): 16GB

**Additional context**
There appear to be solutions for this issue. I hope that such solutions are feasible in Minecraft.

**Comment by rre36** [comment]
TAA flickering always happens and may or may not improve with future updates, especially when its a worst case scenario like in your scene.
