### ISSUE TITLE
more desaturated fog while rainin

### ISSUE THREAD

**Issue by andywithcatz** [rre36/ShaderpackIssueTracker#8]
**Is your feature request related to a problem? Please describe.**
too blue for me eyes :harold:

**Describe the solution you'd like**
make it less blue

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions to this problem I suggested

**Additional context**
![2021-03-01_09 55 54](https://user-images.githubusercontent.com/57657561/109470242-d51bd500-7a77-11eb-870e-d20f535b7606.png)
blue fog

**Comment by rre36** [comment]
Included with 4.0 T3
