### ISSUE TITLE
Soft Voxels Lite: Conduits emit no light

### ISSUE THREAD

**Issue by Lolothepro** [rre36/ShaderpackIssueTracker#81]
**Describe the bug**
Soft Voxels Lite: Conduits emit no light

**Screenshots**

![2023-06-12_20 21 53](https://github.com/rre36/ShaderpackIssueTracker/assets/68275908/850f6fdb-5f44-4706-ba93-62f3a401f3a8)

**Environment :**
Optifine Version: 1.20_HD_U_I5_pre3
Minecraft Version: 1.20.1
Shaderpack Version: 2.0
Graphics Card and Driver Version: NVIDIA 535.43.02 | GTX 1070
Operating System: Ubuntu 22.04
CPU: Ryzen 5 1600
Amount of System Memory (total and assigned to Java): 4Go/16Go

**Comment by rre36** [comment]
Didnt know these existed lol
Those *might* be rendered as entities tho, in that case they wont be able to contribute any worldspace lighting anyways

**Comment by rre36** [comment]
These blocks are indeed rendered as entities, which means they can't be properly voxelised atm, this might change in the future but for now this cannot be fixed.
