### ISSUE TITLE
Kappa: SSPT emits onto reflective metals as if they were diffuse

### ISSUE THREAD

**Issue by SinanAkkoyun** [rre36/ShaderpackIssueTracker#83]
**Describe the bug**
The SSPT indirect lighting system treats metals as if they were diffuse materials. Given that calculating reflections would only result in fireflies, I think it would be best to kill the ray when hitting highly reflective metals if possible

**To Reproduce**
1. Enable SSPT in Kappa
2. Load VNR resourcepack
3. Place emitting block onto iron blocks

**Expected behavior**
The metal should either reflect the screen space rays or kill them

**Screenshots**
![image](https://github.com/rre36/ShaderpackIssueTracker/assets/43215895/ba00c262-c5a0-4b38-935d-362b752c5622)

**Environment (please complete the following information):**
Iris Version: 1.20
Minecraft Version: 1.20.2
Shaderpack Version: Kappa_v5.2
Operating System: Windows 11

**Comment by rre36** [comment]
That's part of a magic number adjustment that prevents metals from becoming pitch black in dark areas

**Comment by SinanAkkoyun** [comment]
Ah, I see
Thanks!
