### ISSUE TITLE
Smooth normals per-vertex

### ISSUE THREAD

**Issue by SinanAkkoyun** [rre36/ShaderpackIssueTracker#84]
**Is your feature request related to a problem? Please describe.**
Hello, thank you for the shaderpack!
I am developing a custom smooth mesh renderer and encountered that your shader might assume that all vertices share the same normal (they did before, my recent PR in Iris was merged to allow for custom per-vertex normals)
Here is a screenshot:
![image](https://github.com/rre36/ShaderpackIssueTracker/assets/43215895/78025906-91af-49f4-86fc-93bcd5ba4499)

And here with for example Complementary Reimagined (BSL and vanilla also supports smooth normals)
![image](https://github.com/rre36/ShaderpackIssueTracker/assets/43215895/f8797bb9-435a-4839-b8cb-152ebea0c220)

It looks as if the shader is picking one vertex normal and sticks with it for the whole face.

Of course, as this is very neiche, the priority might be very low for this, and if you don't want to implement it I understand. However, if you decide not to, could you please give me one sentence on where I would need to look in the shaderpack files to modify it myself? I don't understand the mc shader pipeline yet

**Describe the solution you'd like**
It would be really nice if you could implement a lerp between all three vertex normals, as with smooth shading each vertex has a different one

**Describe alternatives you've considered**
Switch to another shaderpack :< but I love Kappa and its true metals, great SSPT and amazing post-processing effects

**Additional context**
Here is an example for when I export the mesh with flat normals, oh boy does your shader look amazing (I hide the flat faces in this screenshot with DoF)
![image](https://github.com/rre36/ShaderpackIssueTracker/assets/43215895/bba47f55-67f6-4dc7-932f-8bde5107ff68)

Thank you very much! :)

**Comment by rre36** [comment]
All faces are assumed to be flat and are interpolated as such in my packs, since that is the case with vanilla rendering. I might change this in the future though if cases like yours are more common.

**Comment by SinanAkkoyun** [comment]
Thank you for the quick answer

I am trying to do the modification locally, I replaced every `flat in` and `flat out` vec3 normal occurence. Do you mind telling me roughly where else to look?

**Comment by SinanAkkoyun** [comment]
I found everything I need, I simply had to remove the `flat` keyword for the TBN too :)
