### ISSUE TITLE
Held 1st person item is always dark

### ISSUE THREAD

**Issue by SinanAkkoyun** [rre36/ShaderpackIssueTracker#85]
**Describe the bug**
All items held in hand are rendered with a constant shadow on top. When one sneaks, it quickly flashes away for a couple of frames, then it's back to being darker again
This maybe has something to do with the self shadowing and the first person projection matrix messing with it

**To Reproduce**
1. Use MC 1.20.1 and the latest Kappa shader
2. Hold an item and sneak

**Screenshots**
![image](https://github.com/rre36/ShaderpackIssueTracker/assets/43215895/65bb3810-5bfb-486c-953a-6d9fa0ae2f1b)
unsneaked (dark)

![image](https://github.com/rre36/ShaderpackIssueTracker/assets/43215895/fcd539a9-b193-40da-bbf3-a06365f4f1ba)
right when sneaking (it's very difficult to catch that frame, in game the whole block is being lit correctly at those frames)

It seems as if some angles semi work when looking in weird directions
![image](https://github.com/rre36/ShaderpackIssueTracker/assets/43215895/363fc944-fcfd-49c5-a51d-46eeccc3e28a)

**Environment (please complete the following information):**
Iris
Minecraft Version: 1.20.1
Shaderpack Version: Kapa v5.2
Operating System: Windows 11

**Additional context**
I totally get if this has no high priority, just wanted to document it :)

**Comment by mcbabyguo** [comment]
哈哈哈哈哈

**Comment by rre36** [comment]
Thats just self-shadowing of the player most of the time, not a bug per-se.
