### ISSUE TITLE
Improper shading on modded non-full blocks

### ISSUE THREAD

**Issue by CIIIR** [rre36/ShaderpackIssueTracker#87]
**Describe the bug**
Modded stairs and other non-full blocks rendering shadows as if they are full blocks

**To Reproduce**
1. Install forge version 1.20.1-forge-47.1.44
2. Download Biomes 'O Plenty and Create mod (and their dependencies), Rubidium and Oculus
3. View stairs and other non-full block items from Biomes 'O Plenty and Create to see the glitch

**Expected behavior**
I expect there to not be a shadow behind the stairs, behind the half-slabs, and under the Create mod copycat block

**Screenshots**
![2023-08-28_18 36 59](https://github.com/rre36/ShaderpackIssueTracker/assets/115760661/6998e319-6b5a-4165-b07b-b9691ab36a52)
![2023-08-28_18 36 47](https://github.com/rre36/ShaderpackIssueTracker/assets/115760661/8466fbc3-48a0-4a09-a528-7f8290a5f2fe)
![2023-08-28_18 36 32](https://github.com/rre36/ShaderpackIssueTracker/assets/115760661/f877d27f-0f95-4ce4-a8ae-09f84659c304)
First image is vanilla, second is SEUS PTGI HRR 3 (as an example to show other shaders work on my system), the last is vanilla. The blocks I used are from create mod on the left, vanilla in the middle, and biomes o plenty on the right. The block above the stairs on the create mod side is a copycat block.

**Environment (please complete the following information):**
Rubidium Version: 0.6.5
Oculus Version: 1.6.4
Minecraft (Forge) Version: 1.20.1-forge-47.1.44
Shaderpack Version: Soft Voxels Lite v2.0
Graphics Card and Driver Version: Nvidia RTX 3060, GeForce version 537.13
Operating System: Windows 10
CPU: AMD Ryzen 5 5600x
Amount of System Memory (total and assigned to Java): 12 GB assigned, 16 GB total

**Additional context**
I'm only using Oculus because OptiFine doesn't seem to work properly with forge yet.
Not sure if OptiFine has this problem with modded blocks as well

Also this is my first time making a report like this so I hope I included all the information needed!

**Comment by rre36** [comment]
Modded blocks are not mapped by default, PTGI ignores everything it doesn't know, I dont. Not a bug.
You can manually add modded blocks to the shaderpacks block.properties file to get proper mappings.
