### ISSUE TITLE
Darkness around the world

### ISSUE THREAD

**Issue by seriousfreezing** [rre36/ShaderpackIssueTracker#88]
**Describe the bug**
All the blocks are almost black during the day. This is solved in two ways: by placing a block that emits light (but only around it) or by deactivating the world time animation.

**To Reproduce**
1. Activate shaders (in the latest version)
2. Choose any preset you like and you're done

**Expected behavior**
I was supposed to be able to see the blocks normally, even during the day

**Screenshots**
![2023-08-29_19 45 52](https://github.com/rre36/ShaderpackIssueTracker/assets/66693072/0b8e0d67-06a6-48b9-81be-319b5fe1dccd)

**Environment (please complete the following information):**
Sodium Version: 0.4.10
Minecraft Version: 1.19.4
Shaderpack Version: 5.2
Graphics Card and Driver Version: RTX 3050 laptop with Driver 537.13
Operating System: Windows 11 Home
CPU: Intel I5-11400h
Amount of System Memory (total and assigned to Java): 8gb

**Additional context**
There are also some mini-flickers when pausing the game

**Comment by rre36** [comment]
Looks like either outdated iris or trying to run an iris-exclusive pack on optifine. Also no mention of the used shaderpack.
