### ISSUE TITLE
Nostalgia VX: Colour lighting bug

### ISSUE THREAD

**Issue by hibreck** [rre36/ShaderpackIssueTracker#90]
**Describe the bug**
Problem with lighting in Nostalgia VX p10b. When any block that emits light is in front of coloured glass, or surrounded by coloured glass, a bug occurs with incorrect light emission, or lack of colour. This bug only occurs with coloured glass panels.

**To Reproduce**
1. Select all coloured glass panels that are in the game.
2. Place the light emitting blocks separately for each coloured panel.
3. Place each coloured panel around a light source.
4. Place a white wall in front of all light sources to see the colours emitted.
5. See the bug.

**Screenshots**
![Base Profile Screenshot 2023 11 17 - 22 04 21 74](https://github.com/rre36/ShaderpackIssueTracker/assets/83366491/1f4d3859-7e0b-48d0-b1c0-de1bbcef6a76) The red glass panel does not give off any colour at all.
![Base Profile Screenshot 2023 11 17 - 22 04 59 42](https://github.com/rre36/ShaderpackIssueTracker/assets/83366491/609f2e23-4a46-454c-8aad-b75d415e67fb)For some reason, the blue glass panel highlights the green colour, although it should be blue like the blue glass block
![Base Profile Screenshot 2023 11 17 - 22 15 23 50](https://github.com/rre36/ShaderpackIssueTracker/assets/83366491/8e2ba59f-2da0-4d53-8cad-0b97792005b0)The lime glass panel gives off a warm white colour, although it is supposed to be lime.
![Base Profile Screenshot 2023 11 17 - 22 15 55 54](https://github.com/rre36/ShaderpackIssueTracker/assets/83366491/dae95ebc-5e2c-40e4-8ac7-63f3c91b46cb)For example, yellow works perfectly.
![Base Profile Screenshot 2023 11 17 - 22 16 32 77](https://github.com/rre36/ShaderpackIssueTracker/assets/83366491/7a166571-6b09-4d32-9d85-aec07c41ae6d)Orange glass panel emits red colour when it should be orange
![Base Profile Screenshot 2023 11 17 - 22 17 05 88](https://github.com/rre36/ShaderpackIssueTracker/assets/83366491/4456846a-e068-4415-a225-c2d796c541e9)The purple panel highlights the yellow, although it should be purple. 

I'm not going to list all the other colour panels, as it would make this post too long. But the problem is clear, and you need to check all the colours.

**Environment:**
Iris Version: 1.6.10
Sodium Version: 0.5.3
Minecraft Version: 1.20.1
Shaderpack Version: Nostalgia VX P10b
Graphics Card and Driver Version: RTX 3080 ti Driver(546.01)
Operating System: Windows 11 23h2
CPU: AMD Ryzen 5600x
Amount of System Memory (total and assigned to Java): 64GB total, and for Java assigned 13GB

**Additional context**

In the previous version of p8c that I used before, all the glass panels worked correctly, but in p10b it is broken. I would be very grateful if this problem could be fixed as soon as possible. Thank you for your work)

**Comment by hibreck** [comment]
I spent money on KappaPt p17b, hoping that it would fix this, but it also has this problem. I'll try the new version of nostalgia vx p10c tomorrow, but I think it will be useless. 

I also found another bug with the carpets. Both shaders have a problem with it. The carpets somehow emit light in the dark. I noticed it when I used a gray carpet.

**Comment by rre36** [comment]
Glass panes specifically aren't supported atm because they're a bit of a pain to map due to all the shape variations. The thing about the carpets is either a bug or some resourcepack issue if you're using labpbr emission

**Comment by hibreck** [comment]
> Glass panes specifically aren't supported atm because they're a bit of a pain to map due to all the shape variations. The thing about the carpets is either a bug or some resourcepack issue if you're using labpbr emission

So I understand that in the future you will remove the color emission function of the glass panels from the package?

Will you fix it anyway? If not, it will be a not good. It will be necessary to rollback to 1.19 and p8c based on Optifine. Where it still worked properly.

**Comment by rre36** [comment]
More like they aren't working properly atm and never really did before as they were just treated as full cubes and in addition to that there are some occasional atlas uv issues atm, which leads to the incorrect tinting you're seeing.

**Comment by rre36** [comment]
Should be resolved with latest version.
