### ISSUE TITLE
After hitting a mob, the texture of the font covers the entire screen, but it returns to normal after a few seconds.

### ISSUE THREAD

**Issue by EuroDai** [rre36/ShaderpackIssueTracker#92]
**Describe the bug**
Every time I hit a mob, the font texture covers the entire screen and all blocks turn to a weird look, but it returns to normal after a few seconds, and this error also occurs randomly at other times. No matter which language is used, or whether the Unicode font is forced, this problem still occurs.

**To Reproduce**
hit a mob

**Expected behavior**
fix this bug

**Screenshots**
![2024-01-20_11 11 58](https://github.com/rre36/ShaderpackIssueTracker/assets/122048770/85031bc0-32e8-4e49-8f57-000cc4717b8e)
![2024-01-20_11 12 01](https://github.com/rre36/ShaderpackIssueTracker/assets/122048770/691f836f-9172-4eba-a362-da4032cc9c4a)

**Environment (please complete the following information):**
Optifine Version: OptiFine_1.20.1_HD_U_I6 with optifabric-1.14.3
Minecraft Version: 1.20.1
Shaderpack Version: Kappa_v5.2
Graphics Card and Driver Version: NVIDIA GeForce RTX 3070 Laptop GPU, Driver Version 31.0.15.3645
Operating System: Windows 11 23H2 22631.3007
CPU: AMD Ryzen 9 5900HX with Radeon Graphics  
Amount of System Memory (total and assigned to Java): 31.4GB/8GB

**Additional context**
Resorcepacks: SPBR-13_9
Shader Settings: 
resourcepackReflectionsEnabled=true
pomEnabled=true
acesRRTSatOffset=-0.10
pomDepthEnabled=true
Btw is it possible to use a custom skybox resoucepack? I really like the skybox resoucepack I used to add, but the shaderpack seemed to override it.

**Comment by rre36** [comment]
What other mods do you have installed? Does it also happen with just optifine and the resourcepack?
As for the skyboxes, resourcepack skyboxes don't play too well with a full HDR rendering pipeline, hence why I don't support them in this pack.

**Comment by EuroDai** [comment]
> What other mods do you have installed? Does it also happen with just optifine and the resourcepack?
> As for the skyboxes, resourcepack skyboxes don't play too well with a full HDR rendering pipeline, hence why I don't support them in this pack.

It seems that when I enable torohealth 1.20.1 fabric(a mod shows health bar), this bug appears. But it didn't happen on SEUS PTGI HRR 3.

**Comment by rre36** [comment]
Then its a mod issue that happens to mess with texture bindings and SEUS just happens to not produce any noticeable(!) issues with it. Nothing I can fix on my end.
