### ISSUE TITLE
Particles only showing up on water and reflective surfaces I.E Glass 1.19.2

### ISSUE THREAD

**Issue by ShamDogg** [rre36/ShaderpackIssueTracker#95]
**Describe the bug**

GoodEvening, I am using nostalgiaVX on 1.19.2 with Ars Nouveau mod and the spell effect from the book only shows when facing glass or water, mainly any reflective surface.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Preferrably with the F3 Screen being open.

![2024-02-19_17 22 26](https://github.com/rre36/ShaderpackIssueTracker/assets/96894815/3be05990-e4c7-4f4c-b7ef-7749b1335b7b)

![2024-02-19_17 22 47](https://github.com/rre36/ShaderpackIssueTracker/assets/96894815/0490569b-5444-4362-a319-af849c7ecc00)

![2024-02-19_17 22 29](https://github.com/rre36/ShaderpackIssueTracker/assets/96894815/7732ad04-24a7-42cc-abcd-368e54180e1c)

**Environment (please complete the following information):**
Oculus and Rubidium Version: 1.6.9 and 0.6.2c

Minecraft Version: 1.19.2

Shaderpack Version:  NostalgiaVX_P10d_2024-2-19_06.41

Graphics Card and Driver Version: NVIDIA RTX 4060TI
Operating System: AMD RYZEN 7700
CPU:
Amount of System Memory (total and assigned to Java): 7 Gigs

**Additional context**

**Comment by rre36** [comment]
That looks like mod particles, which have a tendency to not be rendered correctly from the mod side of things. If it doesn't happen without mods its up to the mod developer to correct their particle rendering.
