### ISSUE TITLE
Odd water layer reflection on tall grass when looking East

### ISSUE THREAD

**Issue by Barerock** [rre36/ShaderpackIssueTracker#96]
**Describe the bug**
![image](https://github.com/rre36/ShaderpackIssueTracker/assets/38869993/66b7dcd8-5310-42a8-983e-4ecd31aecaa5)
This shows all the info I have. I'm facing south east, but if I turn south thru north this does not show. Also occurs at night with moonlight colors. Changing Y level makes the height of the error change, and is especially noticeable near/on water. It aligns with the horizon, leading me to believe the water reflection gamma or whatever is being applied to the grass.

**To Reproduce**
1. I genuinely have no idea, I noticed while making nights darker - it didn't change at all with color value changes.

**Expected behavior**
More or less for it to look like other grasses and plants when looking east.

**Screenshots**
If applicable, add screenshots to help explain your problem. Preferrably with the F3 Screen being open.

**Environment (please complete the following information):**
Oculus 1.6.15a
Minecraft Version: 1.20.1
Shaderpack Version: v5.0
Graphics Card and Driver Version: NVIDIA GeForce RTX 3070/4.6.0 NVIDIA 551.61
Operating System: Windows 11
CPU: 12th Gen Intel(R) Core(TM) i7-12700KF   3.61 GHz
Amount of System Memory (total and assigned to Java): 32GB RAM/ Java assigned 12,288MB

**Additional context**
I am using physics mod pro, however I have not seen this kind of error while using physics mod in shaders like Rethinking Voxels or other Complementary based shaders. Nor have I seen it in SEUS shader packs or a couple other experimental packs.

**Comment by Barerock** [comment]
![image](https://github.com/rre36/ShaderpackIssueTracker/assets/38869993/c5fe30ce-3931-484a-b588-e67db7a20bb9)
Crouching with waterline matching the odd shading

**Comment by Barerock** [comment]
If I turn reflections off this goes away completely, so I'm right that it's a reflection. Cool.

**Comment by Barerock** [comment]
This is caused by physics mod pro dynamic blocks, turning it off makes this go away. Still have never seen this before, I wonder which side is causing the issue. Other things like sugar cane, another dynamic block, are NOT affected like this and appear normal with shadow movement and everything.

**Comment by rre36** [comment]
If it doesn't happen without the physics mod its most likely an issue caused by it.
